### ISSUE TITLE
Tests do not fail when test case cannot be parsed

### ISSUE THREAD

**Issue by davidalber** [rust-lang-nursery/rustfmt#2287] opened 2017-12-17 22:47 UTC
Reproduction:
1. Create a test file in tests/target that will not be parsed. For example, store the following as test/targets/oops.rs.
```rust
let x = 5;
```
2. Run `cargo test`.

Expected: the tests fail because rustfmt will not format oops.rs.

Actual: the tests report an error for oops.rs, but they still pass. Here's what I see:
```sh
$ cargo test
.
.
.
running 10 tests
test format_lines_errors_are_reported ... ok
test rustfmt_diff_make_diff_tests ... ok
test rustfmt_diff_no_diff_test ... ok
test coverage_tests ... ok
test stdin_formatting_smoke_test ... ok
test string_eq_ignore_newline_repr_test ... ok
test checkstyle_test ... ok
error: expected item, found `let`
 --> tests/target/oops.rs:1:1
  |
1 | let x = 5;
  | ^^^

test system_tests ... ok
test idempotence_tests ... ok
test self_tests ... ok

test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by topecongiro** [comment] 2017-12-18 00:07
I am going to close this since this is a duplicate of #2078. Thank you though for filing an issue and creating an example!

**Closed by topecongiro** 2017-12-18 00:07 UTC
Labels: duplicate
