### ISSUE TITLE
losing arguments in tuple patterns with `..`

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1150] opened 2016-09-06 05:46 UTC
https://github.com/rust-lang/rust/pull/35892/files/c23f4f54dd9554335b8c26e4f546c542d6b2f56e#r77568715

```
-            hir::ItemImpl(.., None, ref ty, _) => {
+            hir::ItemImpl(..) => {
```

**Comment by sinkuu** [comment] 2016-09-06 10:32
dupe of #1021

**Closed** 2016-09-07 03:16 UTC
Labels: bug, duplicate
