### ISSUE TITLE
comments between function prototype and open brace is vanishing

### ISSUE THREAD

**Issue by KeenS** [rust-lang-nursery/rustfmt#1643] opened 2017-06-09 06:13 UTC
this code

```rust
fn some_fn()
// some comment
{}
```

is formatted

```rust
fn some_fn() {}
```

When the function has `where` clause, comments are left but the code gets broken

this code

```rust
fn some_fn<T>() where T: Eq
// some comment
{}
```

gets

```rust
fn some_fn<T>() where T: Eq // some comment {}
```

**Comment by topecongiro** [comment] 2017-06-09 07:20
The first example looks like a duplicate of #458.

**Closed** 2017-08-11 05:07 UTC
Labels: bug, comments
