### ISSUE TITLE
Panic when formatting asm!

### ISSUE THREAD

**Issue by icebit** [rust-lang-nursery/rustfmt#916] opened 2016-04-10 17:18 UTC
When formatting any asm!() instruction, for example:
`			asm!("outb %al, %dx"
				:
				: "{dx}"(self.port), "{al}"(value)
				:
        		: "volatile");
`
 rustfmt panics with
`thread '<main>' panicked at 'explicit panic', /home/voxl/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/errors/mod.rs:360`

**Comment by nrc** [comment] 2016-04-11 22:52
@icebit can you share a whole test case which causes a panic? I can't reproduce with

```
fn main() {
    asm!("outb %al, %dx" : : "{dx}"(self.port), "{al}"(value) : : "volatile");
}
```

**Comment by marcusklaas** [comment] 2016-04-13 21:41
I cannot reproduce this either.. Let's close the issue until further notice.

**Closed by marcusklaas** 2016-04-13 21:41 UTC
Labels: bug
