### ISSUE TITLE
Write mode is not being used.

### ISSUE THREAD

**Issue by carlosgaldino** [rust-lang-nursery/rustfmt#794] opened 2016-01-31 19:29 UTC
Hi,

I have a `rustfmt.toml` with: 

```toml
reorder_imports = true
write_mode = "Overwrite"
```

When I run `fmt` either with `cargo fmt` or `rustfmt` directly the backup files are still created. I already tried to change to `write_mode = "overwrite"` and the same thing happens. The config file is being read though since `reorder_imports = true` works.

Is this a known bug or am I doing something wrong?

Thanks.

P.S.: I'm using `rustfmt` v0.2.1.

**Comment by nrc** [comment] 2016-04-13 03:42
I tested this with master and could not reproduce. I think this has been fixed by @kamalmarhubi  in one of his recent PRs, though I'm not sure which one.

Closing, but feel free to re-open if this is still happening for you.

**Closed by nrc** 2016-04-13 03:42 UTC
Labels: bug

**Comment by kamalmarhubi** [comment] 2016-04-13 04:25
I don't recall doing anything that would have fixed it, but [I *do* have feelings](https://github.com/rust-lang-nursery/rustfmt/issues/871) about `write_mode`-in-`rustfmt.toml` (spoiler: I don't like it!).

**Comment by kamalmarhubi** [comment] 2016-04-13 04:25
:-)
