### ISSUE TITLE
rustfmt 0.8.4 causes code that used to compile to fail to compile

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rustfmt#1533] opened 2017-05-11 18:05 UTC
# Steps to reproduce:

* Clone https://github.com/gimli-rs/gimli/
* Check out this commit: 66e35a140ac127505f40b94d371b75c565dc63d9
* Run `cargo test`
    * it should compile + pass tests
* Install 0.8.4 of `rustfmt`
* Run `cargo fmt`
* Run `cargo test`
    * it results in compilation errors[0]

# Expected results

No compilation errors, tests still passing.

--------------------------------------------------

[0] Here are the compilation errors:

```
$ cargo test
   Compiling odds v0.2.25
   Compiling byteorder v0.5.3
   Compiling leb128 v0.2.1
   Compiling getopts v0.2.14
   Compiling winapi v0.2.8
   Compiling zero v0.1.2
   Compiling winapi-build v0.1.1
   Compiling libc v0.2.20
   Compiling fallible-iterator v0.1.3
   Compiling xmas-elf v0.4.0
   Compiling test-assembler v0.1.5
   Compiling kernel32-sys v0.2.2
   Compiling nodrop v0.1.8
   Compiling arrayvec v0.3.20
   Compiling fs2 v0.2.5
   Compiling memmap v0.4.0
   Compiling object v0.3.0
   Compiling gimli v0.13.0 (file:///home/fitzgen/gimli)
error: unexpected end of macro invocation
    --> src/op.rs:1003:102
     |
1003 |                 panic!("`Evaluation::set_initial_value` was called twice, or after evaluation began.",)
     |                                                                                                      ^

error: Could not compile `gimli`.
Build failed, waiting for other jobs to finish...
error: unexpected end of macro invocation
    --> src/op.rs:1003:102
     |
1003 |                 panic!("`Evaluation::set_initial_value` was called twice, or after evaluation began.",)
     |                                                                                                      ^

error: build failed
```

-------------------------------------------------------------------

Here is the relevant part of the diff after running `cargo fmt`:

```diff
@@ -1004,18 +993,20 @@ impl<'input, Endian> Evaluation<'input, Endian>
     ///
     /// # Panics
     /// Panics if `set_initial_value()` has already been called, or if
     /// `evaluate()` has already been called.
     pub fn set_initial_value(&mut self, value: u64) {
         match self.state {
             EvaluationState::Start(None) => {
                 self.state = EvaluationState::Start(Some(value));
-            },
-            _ => panic!("`Evaluation::set_initial_value` was called twice, or after evaluation began."),
+            }
+            _ => {
+                panic!("`Evaluation::set_initial_value` was called twice, or after evaluation began.",)
+            }
         };
     }
 
     /// Set the enclosing object's address, as used by
     /// `DW_OP_push_object_address`.  If no object address is set, and
     /// the expression uses an opcode requiring the object address,
     /// then evaluation will fail with an error.
     pub fn set_object_address(&mut self, value: u64) {
```

**Comment by fitzgen** [comment] 2017-05-11 18:08
It seems like this is another possible property to fuzz/quickcheck: if it compiles before `rustfmt` then it should compile after `rustfmt`.

For some kind of definition of "pure program", it should also have the same observable behavior, but this seems a bit harder and with diminishing returns compared to the compilation property.

**Comment by nrc** [comment] 2017-05-11 19:21
duplicate of #1528

**Closed by nrc** 2017-05-11 19:21 UTC
Labels: bug, duplicate
