### ISSUE TITLE
 when i use documentation comments ,a line has many words ,it has exception

### ISSUE THREAD

**Issue by sumincy** [rust-lang-nursery/rustfmt#1235] opened 2016-12-08 02:26 UTC
Rustfmt failed at stdin:13: line exceeded maximum length (sorry)

Error: Rustfmt failed at stdin:13: line exceeded maximum length (sorry)

**Comment by nrc** [comment] 2016-12-08 19:18
I think this is expected behaviour - rustfmt doesn't want to change your comment lines, but they are breaking rules that Rustfmt is trying to enforce, so it is telling you that it is failing. In this case the message could be better because it is your fault, not Rustfmt's, but otherwise I think this is fine.

You can solve this by changing the max width option to a larger value or by manually formatting the comments.

I'll close this issue, but let me know if I misunderstood, and I can re-open.

**Closed by nrc** 2016-12-08 19:18 UTC
