### ISSUE TITLE
rustfmt converts vertically aligned function call to  hortizal aligned with new line 

### ISSUE THREAD

**Issue by srinivasreddy** [rust-lang-nursery/rustfmt#1171] opened 2016-09-26 19:40 UTC
```
-        let obligation = traits::Obligation::misc(span,
-                                                  self.body_id,
-                                                  poly_trait_ref.to_predicate());
+        let obligation =
+            traits::Obligation::misc(span, self.body_id, poly_trait_ref.to_predicate());

```

https://github.com/rust-lang/rust/pull/36736/files/1d1168ccea6ee1ede476cefb424c384ba7904bb5#r80407232

another example is here: 
https://github.com/rust-lang/rust/pull/36736/files/1d1168ccea6ee1ede476cefb424c384ba7904bb5#r80407292

and here too. https://github.com/rust-lang/rust/pull/36736/files/1d1168ccea6ee1ede476cefb424c384ba7904bb5#r80407395

**Comment by jseyfried** [comment] 2016-10-03 05:22
I don't think this is a bug -- the new formatting looks better to me.

**Comment by nrc** [comment] 2016-10-11 21:07
Yeah, I'm not sure which I prefer. We'll decide in the style process at some point, I guess.

**Comment by topecongiro** [comment] 2017-05-13 12:23
Closing because this is intended behavior.

**Closed by topecongiro** 2017-05-13 12:23 UTC
Labels: poor-formatting
