### ISSUE TITLE
rustfmt panics with certain bogus code

### ISSUE THREAD

**Issue by mikebenfield** [rust-lang-nursery/rustfmt#2254] opened 2017-12-09 00:51 UTC
```
$ cat trash.rs

{
        ()) => {}
)
$ rustfmt trash.rs
error: incorrect close delimiter: `)`
 --> /Users/mike/trash.rs:3:11
  |
3 |         ()) => {}
  |           ^
  |
note: unclosed delimiter
 --> /Users/mike/trash.rs:2:1
  |
2 | {
  | ^

error: unexpected close delimiter: `)`
 --> /Users/mike/trash.rs:4:1
  |
4 | )
  | ^

thread 'main' panicked at 'Box<Any>', .cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.59.1/src/parse/mod.rs:220
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by topecongiro** [comment] 2017-12-09 02:04
A duplicate of #753, closing.

**Closed by topecongiro** 2017-12-09 02:04 UTC
Labels: duplicate
