### ISSUE TITLE
An empty last line of block comments should not become a line comment

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#683] opened 2015-12-09 20:12 UTC
e.g.,

```
/*
 * hello
 */
```

should become

```
// hello
```

not

```
// hello
//
```

**Comment by marcusklaas** [comment] 2015-12-09 21:22
This seems like a duplicate of https://github.com/rust-lang-nursery/rustfmt/issues/539.

**Closed** 2015-12-09 21:25 UTC
Labels: comments, duplicate
