### ISSUE TITLE
Splitting a function call with a single argument onto multiple lines

### ISSUE THREAD

**Issue by jgouly** [rust-lang-nursery/rustfmt#2016] opened 2017-09-30 15:31 UTC
This code (I included all of it, so it actually compiles with rustc -Zno-trans)

    trait Foo<T> {
      fn write(&self, val: u32);
      fn read(&self) -> u32;
    }
    
    struct I {
      port: Foo<u32>,
    }
    
    const AAAAAAAAAAA: u32 = 0;
    const BBBBBBBBBBBBB: u32 = 0;

    impl I {
      fn init(&self) {
        let abcdefghi = AAAAAAAAAAA;
        self.port.write(self.port.read() | BBBBBBBBBBBBB | abcdefghi);
        let abcdefgh = AAAAAAAAAAA;
        self.port.write(self.port.read() | BBBBBBBBBBBBB | abcdefgh);
      }
    }
    
    fn main() {}

When running it through rustfmt --write-mode=diff it shows:

     impl I {⏎
       fn init(&self) {⏎
         let abcdefghi = AAAAAAAAAAA;⏎
    -    self.port.write(self.port.read() | BBBBBBBBBBBBB | abcdefghi);⏎
    +    self.port.write(⏎
    +      self.port.read() | BBBBBBBBBBBBB | abcdefghi,⏎
    +    );⏎
         let abcdefgh = AAAAAAAAAAA;⏎
         self.port.write(self.port.read() | BBBBBBBBBBBBB | abcdefgh);⏎
       }⏎

I'm unsure why that line was split. It's only 66 characteres. The line below that wasn't split was 65 characters. Also it inserted an extra trailing comma.

    $ rustfmt --version
    0.9.0-nightly ( )

**Comment by nrc** [comment] 2017-10-05 01:38
Could you check to see if this is still a problem on rustfmt-nightly? (or using rustfmt compiled from master). I expect it is fixed now (we have a heuristic for splitting function calls on the length of the arguments as well as the length of the whole line, but I think this case (a single argument) does not apply the heuristic now).

Please comment if this is still an issue and I'll reopen.

**Comment by jgouly** [comment] 2017-10-06 17:10
I ran cargo install --force rustfmt-nightly.

    $ rustfmt --version
    0.2.8-nightly ( )

I still get the line splitting.

I also had to set DYLD_LIBRARY_PATH due to 'dyld: Library not loaded: @rpath/libsyntax-bdb57066596ca7b3.dylib'. But that's another issue.

**Comment by nrc** [comment] 2017-10-07 04:39
Re-opening (though I'm sure I saw a PR fixing this - ping @topecongiro )

**Comment by topecongiro** [comment] 2017-10-07 05:09
Hmm, I could not reproduce this with nightly-0.2.8. I get:
```rust
        self.port
            .write(self.port.read() | BBBBBBBBBBBBB | abcdefghi);
        self.port.write(self.port.read() | BBBBBBBBBBBBB | abcdefgh);
```
The above is fine since the first chain has 61 chars whereas the second one has 60 chars (`chain_one_line_max` is 60 by default).

**Comment by jgouly** [comment] 2017-10-07 19:34
I don't get why it splits at all since the line fits into 80 chars?

**Closed** 2017-11-02 20:46 UTC
