### ISSUE TITLE
Fails to format if struct field is followed by a new line and a comment

### ISSUE THREAD

**Issue by SamWhited** [rust-lang-nursery/rustfmt#1352] opened 2017-03-04 20:34 UTC
Formatting the following:

```rust
struct Interface {
    domain: Option<String>,
    // Test
}
```

Instead of formatting, it outputs:

> Rustfmt failed at stdin:2: left behind trailing whitespace (sorry)

You can try it by clicking the format button here: https://play.rust-lang.org/?gist=26f47925b9bd8943b8d17a8e110f3e64&version=stable&backtrace=0

This is similar and may be related to #878, but I thought it was distinct enough to deserve its own issue and couldn't find anything identical.

**Comment by nrc** [comment] 2017-03-05 19:28
Duplicate of #457

**Closed by nrc** 2017-03-05 19:28 UTC

**Comment by SamWhited** [comment] 2017-03-05 20:15
This isn't actually a duplicate of that issue (in this case it actually fails, as opposed to that similar case where you just get output that's not quite right), but since they are so similar maybe it makes sense to track them both in the same place.
