### ISSUE TITLE
Question: Shouldn't this return a non-zero exit code?

### ISSUE THREAD

**Issue by respeccing** [rust-lang-nursery/rustfmt#901] opened 2016-04-03 11:27 UTC
Shouldn't this return a non-zero exit code?

```bash
$ cat a.rs| ./rustfmt ; echo $?
stdin:4:5: 4:10 error: expected one of `.`, `;`, `?`, `}`, or an operator, found `panic`
stdin:4     panic!();
            ^~~~~
fn main() {
    println!("Hello, world!<anon>:3");
    12
    panic!();
}
0
```
(note: stderr and stdout are both present in the above)

This is: `a.rs`
https://play.rust-lang.org/?gist=72b057fbddf6d3c34152ab70b0ef8abf&version=stable&backtrace=2

rustfmt commit tested: d9ccec6f82fb4d58e41b78de6be530de72e4db00

$ rustc -Vv
!! executing '/home/zazdxscf/build/1nonpkgs/rust/rust//x86_64-unknown-linux-gnu/stage2/bin//rustc' with args: '-Vv'
rustc 1.9.0-dev (f2285bdaf 2016-04-02)
binary: rustc
commit-hash: f2285bdaf57e9cb56120902ae4b3b0a26d761f31
commit-date: 2016-04-02
host: x86_64-unknown-linux-gnu
release: 1.9.0-dev

Affects: https://github.com/rust-lang/rust-playpen/issues/194
(But that should probably discard the stderr output, rather than depend on a potential exit code, right?)

**Comment by nrc** [comment] 2016-04-04 04:50
cc @matklad

**Comment by matklad** [comment] 2016-04-04 06:35
Yep, `rustfmt` currently returns non-zero status only when command line arguments are invalid. I think this is a duplicate of https://github.com/rust-lang-nursery/rustfmt/issues/150. I am working on it (https://github.com/rust-lang-nursery/rustfmt/pull/897 is prerequisite) :)

**Comment by nrc** [comment] 2016-04-04 21:32
Thanks for the comment. Closing as a dup of #150

**Closed by nrc** 2016-04-04 21:32 UTC
Labels: bug
