### ISSUE TITLE
rustmft crash

### ISSUE THREAD

**Issue by gyn** [rust-lang-nursery/rustfmt#1731] opened 2017-06-19 14:15 UTC
Hi guys,
I tried to use rustfmt directly to format a rust file but saw crash.
The output is :
> [yanan@yanan-PC pascals-triangle]$ rustfmt /home/yanan/workspace/exercism/rust/pascals-triangle/src/lib.rs 
> error: unknown start of token: `
>  --> /home/yanan/workspace/exercism/rust/pascals-triangle/src/lib.rs:1:57
>   |
> 1 | Error: unable to find a config file for the given path: `/home/yanan/workspace/exercism/rust/pascals-triangle/src`
>   |                                                         ^
> 
> thread 'main' panicked at 'Box<Any>', .cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.59.1/src/parse/lexer/mod.rs:86
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> [yanan@yanan-PC pascals-triangle]$ rustfmt --version
> 0.9.0-nightly ( )
> [yanan@yanan-PC pascals-triangle]$ 

Should I always create a rustfmt.toml for rustfmt command. By the way cargo fmt command works for me.
Thanks.
Yanan

**Comment by topecongiro** [comment] 2017-06-19 14:42
Could you reproduce this bug by using rustfmt from the current master?

**Comment by gyn** [comment] 2017-06-20 00:10
Hi topecongiro,
rustfmt-nightly and master produced similar output.
This is from rustfmt-nightly :

> [yanan@yanan-PC pascals-triangle]$ rustfmt /home/yanan/workspace/exercism/rust/pascals-triangle/src/lib.rs
> error: unknown start of token: `
>  --> /home/yanan/workspace/exercism/rust/pascals-triangle/src/lib.rs:1:57
>   |
> 1 | Error: unable to find a config file for the given path: `/home/yanan/workspace/exercism/rust/pascals-triangle/src`
>   |                                                         ^
> 
> thread 'main' panicked at 'Box<Any>', /checkout/src/libsyntax/parse/lexer/mod.rs:85
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> [yanan@yanan-PC pascals-triangle]$ rustfmt --version
> 0.1.4-nightly ( )

And the one from master :

> [yanan@yanan-PC pascals-triangle]$ rustfmt /home/yanan/workspace/exercism/rust/pascals-triangle/src/lib.rs
> error: unknown start of token: `
>  --> /home/yanan/workspace/exercism/rust/pascals-triangle/src/lib.rs:1:57
>   |
> 1 | Error: unable to find a config file for the given path: `/home/yanan/workspace/exercism/rust/pascals-triangle/src`
>   |                                                         ^
> 
> thread 'main' panicked at 'Box<Any>', /checkout/src/libsyntax/parse/lexer/mod.rs:85
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> [yanan@yanan-PC pascals-triangle]$ rustfmt --version
> 0.1.4-nightly (a87a445 2017-06-19)

Regards,

Yanan

**Comment by topecongiro** [comment] 2017-06-20 03:22
Thank you! That is unfortunate...
If it is possible, could you give a link to your repository so that I could reproduce it?

**Comment by gyn** [comment] 2017-06-20 12:58
Hi topecongiro,
I found this is caused by AnacondaRust, a rust plugin for sublime text. It invoke rustfmt program to format the source code but overwrite the source code with error output. So if I used rustfmt with this corrupted file, I could see this error.
Sorry for the confusion I made.
Yanan

**Comment by topecongiro** [comment] 2017-06-20 13:49
@gyn Thank you! I think rustfmt should not panic even if the rust file is broken.

The minimal example to reproduce the bug:
```rust
`
```
That is, a single grave accent!

**Comment by topecongiro** [comment] 2017-06-20 14:07
Looks like this is already reported on #753 and  #899. I will close this issue in favor of #753.
@gyn Thank your your report!

**Closed by topecongiro** 2017-06-20 14:07 UTC
Labels: bug
