### ISSUE TITLE
Prepended underscores in macro identifiers are incorrectly removed

### ISSUE THREAD

**Issue by allengeorge** [rust-lang-nursery/rustfmt#2585] opened 2018-04-01 10:50 UTC
Running `cargo +nightly fmt` on the following code breaks it:

#### Original
```rust
macro_rules! assert_success_data {
    ($__r:expr, $__p:pat, $__x:expr) => {
        match $__r {
            Response::Success($__p) => $__x,
            __u => assert!(false, format!("unexpected response {:?}", __u)),
        }
    };
}
fn main() {
    println!("Hello, world!");
}
```

#### Formatted
```rust
macro_rules! assert_success_data {
    ($__r:expr, $__p:pat, $__x:expr) => {
        match $r { // <---- PREPENDED UDERSCORES REMOVED
            Response::Success($p) => $x, // <---- PREPENDED UNDERSCORES REMOVED
            __u => assert!(false, format!("unexpected response {:?}", __u)),
        }
    };
}
fn main() {
    println!("Hello, world!");
}
```

Specifically, it seems like `$__r`, `$__p` and `$__x` had their initial underscores removed. What's interesting is that `__u` in the next match arm is untouched.

`rustfmt` version: `0.3.8-nightly (346238f 2018-02-04)`

**Comment by topecongiro** [comment] 2018-04-01 13:54
Thanks for filing an issue. I am going to close this as this is a duplicate of #2560.

**Closed by topecongiro** 2018-04-01 13:54 UTC
Labels: duplicate

**Comment by allengeorge** [comment] 2018-04-01 14:35
My bad :/ I should have done a better job of searching open issues. I searched for “underscore”, but should also have searched for “_” and “macro”.

I will take a look at the referenced bug and see how hard it is to actually fix, since it’s marked as a “good first issue”.

Thank you!

________________________________

**Comment by topecongiro** [comment] 2018-04-01 14:41
@allengeorge No worry! Also the issue is already fixed on the current master :)

**Comment by allengeorge** [comment] 2018-04-01 14:48
Ah :) TY!

________________________________
