### ISSUE TITLE
rustfmt-nightly 0.3.4 deleting from macro bodies

### ISSUE THREAD

**Issue by commandline** [rust-lang-nursery/rustfmt#2344] opened 2018-01-05 20:21 UTC
I noticed the deprecation warning from rustfmt and install rustfmt-nightly 0.3.4. Seems to work well *except* it clobbers some of my macro bodies.

See https://gist.github.com/anonymous/893e7bf6b3e8b3841052098edc07c25e for an example.

Asked in the serde room in case this was something specific to the json macro. Looks like the issue is only reproduce-able when the result of the macro is assigned in a let statement. If the json! macro is passed into a function or used as a return expression in a block or function, rustfmt-nightly doesn't mangle the macro body.

**Comment by topecongiro** [comment] 2018-01-07 04:06
Closing as a duplicate of #2338.

**Closed by topecongiro** 2018-01-07 04:06 UTC
