### ISSUE TITLE
[stdsimd] cargo fmt --all succeeds but subsequent cargo fmt --all -- --check fails

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2787] opened 2018-06-15 12:17 UTC
With this PR `cargo fmt --all` currently outputs nothing and returns `0` (`EXIT_SUCCESS`). A subsequent call to `cargo fmt --all -- --check` returns `101` and **sometimes** (1/5 times) prints the following diff. Other times it doesn't print anything, just fails with that error (e.g. like here: https://travis-ci.org/rust-lang-nursery/stdsimd/jobs/392688468#L472): 

```diff
Diff in stdsimd/crates/stdsimd-verify/src/lib.rs at line 95:
 
 fn to_type(t: &syn::Type) -> proc_macro2::TokenStream {
     match *t {
-        syn::Type::Path(ref p) => match extract_path_ident(&p.path).to_string().as_ref() {
-            "__m128" => quote! { &M128 },
-            "__m128d" => quote! { &M128D },
-            "__m128i" => quote! { &M128I },
-            "__m256" => quote! { &M256 },
-            "__m256d" => quote! { &M256D },
-            "__m256i" => quote! { &M256I },
-            "__m64" => quote! { &M64 },
-            "bool" => quote! { &BOOL },
-            "f32" => quote! { &F32 },
-            "f64" => quote! { &F64 },
-            "i16" => quote! { &I16 },
-            "i32" => quote! { &I32 },
-            "i64" => quote! { &I64 },
-            "i8" => quote! { &I8 },
-            "u16" => quote! { &U16 },
-            "u32" => quote! { &U32 },
-            "u64" => quote! { &U64 },
-            "u8" => quote! { &U8 },
-            "CpuidResult" => quote! { &CPUID },
-            s => panic!("unspported type: {}", s),
-        },
+        syn::Type::Path(ref p) => {
+            match extract_path_ident(&p.path).to_string().as_ref() {
+                "__m128" => quote! { &M128 },
+                "__m128d" => quote! { &M128D },
+                "__m128i" => quote! { &M128I },
+                "__m256" => quote! { &M256 },
+                "__m256d" => quote! { &M256D },
+                "__m256i" => quote! { &M256I },
+                "__m64" => quote! { &M64 },
+                "bool" => quote! { &BOOL },
+                "f32" => quote! { &F32 },
+                "f64" => quote! { &F64 },
+                "i16" => quote! { &I16 },
+                "i32" => quote! { &I32 },
+                "i64" => quote! { &I64 },
+                "i8" => quote! { &I8 },
+                "u16" => quote! { &U16 },
+                "u32" => quote! { &U32 },
+                "u64" => quote! { &U64 },
+                "u8" => quote! { &U8 },
+                "CpuidResult" => quote! { &CPUID },
+                s => panic!("unspported type: {}", s),
+            }
+        }
         syn::Type::Ptr(syn::TypePtr { ref elem, .. })
         | syn::Type::Reference(syn::TypeReference { ref elem, .. }) => {
             let tokens = to_type(&elem);
```

We should add to CI a check that after formatting `cargo fmt --all -- --check` should return `true` and if not fail the integration tests.

**Comment by gnzlbg** [comment] 2018-06-15 12:17
cc @nrc

**Comment by gnzlbg** [comment] 2018-06-19 09:27
update: the integration tests for `cargo fmt --all -- --check` have been merged in https://github.com/rust-lang-nursery/rustfmt/commit/75d46b1e12650ef7b8ea07182f67d15312fb9da0

Once this is fixed those tests should prevent it from becoming broken again.

**Comment by topecongiro** [comment] 2018-08-04 09:14
This is still reproducible with the latest rustfmt ().

Why do `cargo fmt --all` or `cargo fmt --all -- --check` return 101 in the first place? AFAICT in the latest rustfmt there is no code path that returns 101 exit code...

**Comment by topecongiro** [comment] 2018-08-04 09:38
I figured that rustfmt silently crashes when formatting [stdsimd/crates/src/lib.rs](https://github.com/rust-lang-nursery/stdsimd/blob/51904cd6e53eaeae2450a96fc83f0e5b7f813504/crates/stdsimd/src/lib.rs). In particular, [this module declaration](https://github.com/rust-lang-nursery/stdsimd/blob/51904cd6e53eaeae2450a96fc83f0e5b7f813504/crates/stdsimd/src/lib.rs#L23-L24) seems to break rustfmt.

**Comment by topecongiro** [comment] 2018-08-04 10:08
Ok, so the actual file that breaks rustfmt is [stdsimd/stdsimd/mod.rs](https://github.com/rust-lang-nursery/stdsimd/blob/51904cd6e53eaeae2450a96fc83f0e5b7f813504/stdsimd/mod.rs), and the relevant code is [this](https://github.com/rust-lang-nursery/stdsimd/blob/51904cd6e53eaeae2450a96fc83f0e5b7f813504/stdsimd/mod.rs#L60-L73):

```rust
/// ```ignore
/// #[cfg(all(any(target_arch = "x86", target_arch = "x86_64"),
///       target_feature = "avx2"))]
/// fn foo() {
///     #[cfg(target_arch = "x86")]
///     use std::arch::x86::_mm256_add_epi64;
///     #[cfg(target_arch = "x86_64")]
///     use std::arch::x86_64::_mm256_add_epi64;
///
///     unsafe {
///         _mm256_add_epi64(...);
///     }
/// }
/// ```
```

Note that the third line should be prefixed with `#`. I have sent a PR that fixes this to stdsimd (https://github.com/rust-lang-nursery/stdsimd/pull/548).

**Comment by topecongiro** [comment] 2018-08-04 10:09
I am still unsure why rustfmt started to fail silently against invalid code, I guess there is something weird going on inside `syntax::with_globals`?

**Comment by topecongiro** [comment] 2018-08-04 10:30
https://github.com/rust-lang-nursery/rustfmt/issues/2787#issuecomment-410438645 was wrong 😞 It was a pure bug in the rustfmt side. #2895 should fix this.

**Comment by topecongiro** [comment] 2018-08-06 06:04
Closed via #2895.

**Closed by topecongiro** 2018-08-06 06:04 UTC
Labels: bug, p-high

**Comment by gnzlbg** [comment] 2018-08-10 11:56
Did this land on the nightly preview yet? Or could you ping me when it does?

**Comment by nrc** [comment] 2018-08-13 00:49
It hasn't because we've had some problems in the Rust repo. It is in the queue, so as soon as there is a new nightly, it should have this fix in it.
