### ISSUE TITLE
In diff mode, Rustfmt does not insert a file-terminating newline

### ISSUE THREAD

**Issue by octaltree** [rust-lang-nursery/rustfmt#1753] opened 2017-06-26 11:28 UTC
Can I append '\n' before EOF to main.rs made by `echo -n 'fn main() {}' > main.rs`?

**Comment by nrc** [comment] 2017-06-27 16:57
I'm not sure exactly what the request is here. I believe Rustfmt does ensure that a file ends with a single newline. Do you want something more than that? Are there cases where we don't do it (I could believe there are bugs here). If you've found a bug, could you tell me how you run Rustfmt?

**Comment by octaltree** [comment] 2017-06-30 02:26
```
$ cargo  --version
cargo 0.18.0 (fe7b0cdcf 2017-04-24)
```
I made a file with following commands.
```
$ cargo new --bin foo
$ cd foo/
$ echo -n 'fn main() {}' > src/main.rs
```
I uploaded main.rs as [main.txt](https://github.com/rust-lang-nursery/rustfmt/files/1113915/main.txt).

```
$ rustfmt --version
0.9.0-nightly ( )
$ cargo fmt -- --version
0.9.0-nightly ( )
```

In this situation, `cargo fmt -- --write-mode=diff` outputs nothings and responds 0 as status code. After diffing,  `cargo fmt -- --write-mode=overwrite` overwrited it correctly: rustfmt appended '\n' to it.

I checked whether `cargo fmt -- --write-mode=diff` read main.rs or not.
```
$ echo -n 'fn main(){\n}' > src/main.rs
$ cargo fmt -- --write-mode=diff
Diff in /home/octaltree/workspace/a/foo/src/main.rs at line 1:
-fn main(){⏎
-}⏎
+fn main() {}⏎
```

Is there any information missing?

**Comment by nrc** [comment] 2017-07-04 03:46
Looks like this is just an issue with the diff write mode.

**Comment by afshinm** [comment] 2017-11-06 08:36
@nrc I can take this one.

**Comment by afshinm** [comment] 2017-11-11 23:30
@nrc I found the problem but I need your help to find a good solution to solve it. 

The problem is `diff` crate uses `str.lines()` which ignores the last line if it's empty: https://play.rust-lang.org/?gist=276e9980079783b2f406b6f6a4f45fbb&version=stable

That's why diff mode with `echo -n 'fn main() {}'` does not work as expected. My solution is to manually check and see if the the `actual` ends with `\n` and push a mismatch to the results after this loop: https://github.com/rust-lang-nursery/rustfmt/blob/master/src/rustfmt_diff.rs#L47

But I'm not sure if it is a good idea? Let me know what you think.

**Comment by nrc** [comment] 2017-11-12 22:03
@afshinm This sounds like it is a bug in the diff crate and that, if possible, it should be fixed upstream. Do you think it would be possible to fix there?

**Comment by afshinm** [comment] 2017-11-13 07:53
@nrc that's correct. I think the best approach is to fix the problem in upstream rather than in rustfmt. I can close this PR and move it to diff crate.

**Closed** 2017-11-20 01:45 UTC
Labels: good-first-issue
