### ISSUE TITLE
Invalid struct fields with attributes spacing suggestion 

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang-nursery/rustfmt#1956] opened 2017-09-09 20:29 UTC
Input:
```rust
pub struct ErrorPos {
    #[allow(missing_docs)]
    pub row: usize,
    #[allow(missing_docs)]
    pub col: usize,
}
```
suggestion:
```diff
 pub struct ErrorPos {⏎
     #[allow(missing_docs)]⏎
-    pub row: usize,⏎
+    pub row:                    usize,⏎
     #[allow(missing_docs)]⏎
-    pub col: usize,⏎
+    pub col:                    usize,⏎
 }⏎
```

Probably a `struct_field_align_threshold` bug.

rustfmt nightly-0.2.5

**Comment by topecongiro** [comment] 2017-09-10 08:33
Thank you for filing an issue! I will be closing this as this is a duplicate of #1943, and fixed on the current master.

**Closed by topecongiro** 2017-09-10 08:33 UTC
Labels: duplicate
