### ISSUE TITLE
Unexpected indentation for method calls on slice literal.

### ISSUE THREAD

**Issue by jdm** [rust-lang-nursery/rustfmt#3179] opened 2018-11-06 15:46 UTC
Before:
```rust
        let bits = [
            (color, gl::COLOR_BUFFER_BIT),
            (depth, gl::DEPTH_BUFFER_BIT),
            (stencil, gl::STENCIL_BUFFER_BIT),
        ].iter().fold(0, |bits, &(enabled, bit)| bits | if enabled { bit } else { 0 });
```
After:
```rust
        let bits = [
            (color, gl::COLOR_BUFFER_BIT),
            (depth, gl::DEPTH_BUFFER_BIT),
            (stencil, gl::STENCIL_BUFFER_BIT),
        ]
            .iter()
            .fold(0, |bits, &(enabled, bit)| {
                bits | if enabled { bit } else { 0 }
            });
```

**Comment by topecongiro** [comment] 2018-11-07 09:48
This is a duplicate of #3003. Closing as fixed on the master branch.

**Closed by topecongiro** 2018-11-07 09:48 UTC
Labels: duplicate
