### ISSUE TITLE
Inconsistency in formatting for explicit and implicit targets

### ISSUE THREAD

**Issue by jonhoo** [rust-lang-nursery/rustfmt#1606] opened 2017-05-29 16:54 UTC
I've tried to minimize this as much as I can, and have arrived at this:
`src/lib.rs`:
```rust
nodeop_from_impl!(NodeOperator::Sum,
                  grouped::GroupedOperator<grouped::aggregate::Aggregator>);
mod sql;
```
`src/sql.rs`:
```rust
pub fn foo() {
    let new_node = |rel: String,
                    preds: Vec<ConditionTree>,
                    st: &SelectStatement|
     -> QueryGraphNode {
        QueryGraphNode {
            columns: st.fields
                .iter()
                .filter_map(|field| match field {
                                &FieldExpression::Col(ref c) => {
                                    match c.table.as_ref() {
                                        None => {
                        match c.function {
                            // XXX(malte): don't drop aggregation columns
                            None => panic!("No table name set for column {} on {}", c.name, rel),
                        }
                    }
                                    }
                                }
                            })
                .collect(),
        }
    };
}
```
If you run
```console
$ rustfmt --write-mode=overwrite src/lib.rs
```
No errors are printed, the exit code is 0, and no files are changed. The same results from running `cargo fmt`. However, if you run
```console
$ rustfmt --write-mode=overwrite src/sql.rs
```
`src/sql.rs` is significantly reformatted (and for the better).

Note that this does not trigger for all contents of `src/sql.rs`. For example, this file *is* reformatted when calling rustfmt on `src/lib.rs`:
```rust
pub fn foo() {
    let a       =     1 + 2;
}
```

**Comment by jonhoo** [comment] 2017-06-09 18:31
@nrc I think this should potentially be considered a blocker for 0.9.0. It's really unfortunate that formatting some files *undoes* the formatting to others, as you quickly end up with these back-and-forth diffs in commits if people aren't careful.

**Comment by topecongiro** [comment] 2017-06-10 04:33
The issue looks like a duplicate of #1128.

**Comment by jonhoo** [comment] 2017-06-10 16:04
@topecongiro yes, I agree, the two look related.

**Closed** 2017-06-11 22:37 UTC
Labels: bug
