### ISSUE TITLE
rustfmt converts properly fit function call to vertical aligment

### ISSUE THREAD

**Issue by srinivasreddy** [rust-lang-nursery/rustfmt#1170] opened 2016-09-26 19:37 UTC
```
-        Ok(self.confirm_method(span, self_expr, call_expr, self_ty, pick, supplied_method_types))
+        Ok(self.confirm_method(span,
+                               self_expr,
+                               call_expr,
+                               self_ty,
+                               pick,
+                               supplied_method_types))
```

https://github.com/rust-lang/rust/pull/36736/files/1d1168ccea6ee1ede476cefb424c384ba7904bb5#diff-d66943f8e54938955ce02ba6b02eece3L138

**Comment by nrc** [comment] 2016-10-11 21:04
I think we might just have a cutoff at which we use vertical formatting even if we don't hit the width limit, in which case this is not a bug.

**Comment by nrc** [comment] 2016-10-11 21:05
Yeah, `fn_call_width`: https://github.com/rust-lang-nursery/rustfmt/blob/master/src/config.rs#L343

Style team might decide to lose this, but closing this as intended behaviour for now.

**Closed by nrc** 2016-10-11 21:05 UTC
Labels: poor-formatting
