### ISSUE TITLE
Unexpected formatting of if-else inside closure

### ISSUE THREAD

**Issue by jeanm** [rust-lang-nursery/rustfmt#1791] opened 2017-07-16 00:11 UTC
This seems to be related to #1771. Not sure if it's intended behaviour. I find it much easier to understand what's going on when `if` and `else` are aligned:
```diff
  fn main() {⏎
-    something.any(|x|⏎
-        if 1_000_000_000 == 1_000_000_000 {⏎
-            true⏎
-        } else {⏎
-            false⏎
-        }⏎
-    );⏎
+    something.any(|x| if 1_000_000_000 == 1_000_000_000 {⏎
+        true⏎
+    } else {⏎
+        false⏎
+    });⏎
 }⏎
```

```
$ rustfmt --version
0.1.9-nightly (05d043c 2017-07-14)
```

**Comment by topecongiro** [comment] 2017-07-20 03:42
This is an intended behaviour (see https://github.com/rust-lang-nursery/fmt-rfcs/issues/35#issuecomment-289655028), although I agree that the former looks bettern in this case.

**Comment by bluss** [comment] 2017-07-29 12:33
I have an issue with a formatting change in the same vein, but I think it's even worse with `for`. Rust is expression-oriented, but for never evaluates to a useful value, so I think it should **not** be contracted like this:

```diff
@@ -94,12 +86,10 @@ fn zip_default_zip3(b: &mut test::Bencher)
     let ys = black_box(ys);
     let zs = black_box(zs);
 
-    b.iter(|| {
-        for ((&x, &y), &z) in xs.iter().zip(&ys).zip(&zs) {
-            test::black_box(x);
-            test::black_box(y);
-            test::black_box(z);
-        }
+    b.iter(|| for ((&x, &y), &z) in xs.iter().zip(&ys).zip(&zs) {
+        test::black_box(x);
+        test::black_box(y);
+        test::black_box(z);
     })
 }
```

**Comment by stjepang** [comment] 2017-07-31 14:32
I've also found this to be a problem.

Instead of this (rustfmt):
```rust
s.spawn(move || for i in 0..COUNT {
    tx.send(i).unwrap();
});
```

...the following might look better:
```rust
s.spawn(move || {
    for i in 0..COUNT {
        tx.send(i).unwrap();
    }
});
```

IME, the only situation where putting something in between `||` and `{` is sensible is when marking the beginning of an unsafe block:

```rust
s.spawn(move || unsafe {
    // ...
});
```

**Comment by joshtriplett** [comment] 2017-07-31 15:36
This definitely shouldn't happen with `for`. For `if`, it's reasonable in some cases (if the branches don't contain full statements, just expression values), but not in others.

As an aside, I'm also wondering (outside the context of rustfmt) if we should have a lint for conditionals of the form `if cond { true } else { false }`, or vice versa `if cond { false } else { true }`, and suggest changing them to `cond` and `!cond` respectively.

**Comment by philipc** [comment] 2017-07-31 22:08
@joshtriplett There is one in clippy: https://github.com/rust-lang-nursery/rust-clippy/wiki#needless_bool

**Comment by stjepang** [comment] 2017-08-10 23:59
Another example:

```rust
fn transition(&mut self, len: usize, deadline: Option<Instant>) {
    match *self {
        State::TryOnce { closed_count } => if closed_count < len {
            *self = State::Blocked;
        } else {
            *self = State::Disconnected;
        },
        State::SpinTry { closed_count } => if closed_count < len {
            actor::current().reset();
            *self = State::Promise { closed_count: 0 };
        } else {
            *self = State::Disconnected;
        },
    }
}
```

I would prefer:

```rust
fn transition(&mut self, len: usize, deadline: Option<Instant>) {
    match *self {
        State::TryOnce { closed_count } => {
            if closed_count < len {
                *self = State::Blocked;
            } else {
                *self = State::Disconnected;
            }
        }
        State::SpinTry { closed_count } => {
            if closed_count < len {
                actor::current().reset();
                *self = State::Promise { closed_count: 0 };
            } else {
                *self = State::Disconnected;
            }
        }
    }
}
```

**Comment by stjepang** [comment] 2017-08-11 19:48
And in some cases I think this style might be even sort of dangerous.

When glancing over following example, the lack of indentation makes it easy to miss that block is in fact a loop.

```rust
epoch::pin(|scope| loop {
    let head = self.head.load(SeqCst, scope);
    let next = head.deref().next.load(SeqCst, scope);

    if next.is_null() {
        if self.tail.load(SeqCst, scope).as_raw() == head.as_raw() {
            return None;
        }
    } else {
        if self.head
            .compare_and_swap(head, next.with_tag(MULTI), SeqCst, scope)
            .is_ok()
        {
            self.recv_count.fetch_add(1, SeqCst);
            scope.defer_free(head);
            return Some(ptr::read(&next.deref().value));
        }
    }
})
```

Now removing the keyword `loop` would be a hardly visible change, yet it would completely change the flow of the program. This is very concerning to me.

**Comment by stjepang** [comment] 2017-08-12 00:26
Sorry for spamming this thread, but I've just got bitten by this formatting for real.

Here's a concrete scenario where I spent 15 minutes debugging the code and not realizing what went wrong:

```rust
crossbeam::scope(|s| for i in 0..555 {
    s.spawn(move || loop {
        if let Ok(x) = rx.select() {
            assert_ne!(i, x);
            break;
        }
        if let Ok(()) = tx.select(i) {
            break;
        }
    });
    tx.send(!0).unwrap(); // I added this line, expecting it to be run once after the loop ends.
});
```

It took me way too long to realize that I wanted to do the following instead:

```rust
crossbeam::scope(|s| {
    for i in 0..555 {
        s.spawn(move || loop {
            if let Ok(x) = rx.select() {
                assert_ne!(i, x);
                break;
            }
            if let Ok(()) = tx.select(i) {
                break;
            }
        });
    }
    tx.send(!0).unwrap(); // Now that's better!
});
```

Doh! :) I wanted to add that line to end of the lambda, but it actually ended up being in the loop.
Very very subtle!

**Comment by nrc** [comment] 2017-08-13 22:38
I commented on this over on fmt-rfcs at https://github.com/rust-lang-nursery/fmt-rfcs/issues/35#issuecomment-322071999

**Comment by spinda** [comment] 2017-08-18 02:45
Is there any way to turn this off? I really can't stand it, it reminds me of braceless if statements.

**Comment by emilio** [comment] 2017-08-18 07:44
@spinda you can probably just apply https://github.com/rust-lang-nursery/rustfmt/pull/1889 and build locally for now, I guess.

**Comment by nrc** [comment] 2017-11-02 20:28
Fixed by https://github.com/rust-lang-nursery/rustfmt/pull/1877

**Closed by nrc** 2017-11-02 20:28 UTC
