### ISSUE TITLE
Option to format function calls in a struct-construction-like manner

### ISSUE THREAD

**Issue by daboross** [rust-lang-nursery/rustfmt#1011] opened 2016-05-27 03:43 UTC
Often, I'll write a long function chain with some single-argument function calls and one many-argument function call at the end like like this:

``` rust
graphics::Rectangle::new(graphics::color::BLACK).draw(
    block,
    &context.draw_state,
    context.trans(screen_width / 2.0, screen_height / 2.0).flip_v().transform,
    graphics,
);
```

This reasonably represents the arguments, and is easy to read, as far as I can tell. This is especially useful when the code is already very indented. The default reformat for this is as follows:

``` diff
-                graphics::Rectangle::new(graphics::color::BLACK).draw(
-                    block,
-                    &context.draw_state,
-                    context.trans(screen_width / 2.0, screen_height / 2.0).flip_v().transform,
-                    graphics,
-                );
+                graphics::Rectangle::new(graphics::color::BLACK).draw(block,
+                                                                      &context.draw_state,
+                                                                      context.trans(screen_width /
+                                                                                 2.0,
+                                                                                 screen_height /
+                                                                                 2.0)
+                                                                          .flip_v()
+                                                                          .transform,
+                                                                      graphics);
```

This is a lot harder to read, uses more space, and splits up the arguments more. It's acceptable as a default, but it'd be nice to have the option to format, or at to least accept previous formatting of, functions as if they were constructions.

If possible, it'd be awesome to have an option to allow (or force) formatting function calls at the end of a long chain with more than two parameters like a struct construction, as shown above.

I'm not familiar with the rustfmt codebase, but if this is allowed as an addition to the options I'd be willing to try and implement it.

**Comment by daboross** [comment] 2016-05-27 04:22
A few more places this happens in the codebase the above is taken from:

```diff
-                    graphics::Rectangle::new(graphics::color::BLACK).draw(
-                        [min_x - scroll_x, min_y - scroll_y, length_x, length_y],
-                        &context.draw_state,
-                        context.trans(screen_width / 2.0, screen_height / 2.0).flip_v().transform,
-                        graphics,
-                    );
+                    graphics::Rectangle::new(graphics::color::BLACK)
+                        .draw([min_x - scroll_x, min_y - scroll_y, length_x, length_y],
+                              &context.draw_state,
+                              context.trans(screen_width / 2.0, screen_height / 2.0)
+                                  .flip_v()
+                                  .transform,
+                              graphics);
```


```diff
-                self.scroll_start = Some((
-                    self.current_mouse_x + scroll_x - self.screen_width / 2.0,
-                    self.current_mouse_y + scroll_y - self.screen_height / 2.0,
-                ));
+                self.scroll_start = Some((self.current_mouse_x + scroll_x - self.screen_width / 2.0,
+                                          self.current_mouse_y + scroll_y -
+                                          self.screen_height / 2.0));
```

```diff
-                    draw_text(
-                        [x_pos, screen_height * 0.2, width, height * 1.5],
-                        &self.title,
-                        (height * 1.5) as u32,
-                        graphics::color::WHITE,
-                        cache, &context, graphics,
-                    );
+                    draw_text([x_pos, screen_height * 0.2, width, height * 1.5],
+                              &self.title,
+                              (height * 1.5) as u32,
+                              graphics::color::WHITE,
+                              cache,
+                              &context,
+                              graphics);
```

```diff
-        graphics::Text::new_color(color, text_size).draw(
-            text,
-            &mut cache.font,
-            &context.draw_state,
-            context.trans(
-                (x_pos + width / 2.0 - text_width / 2.0).floor(),
-                (y_pos + height / 2.0 - text_height / 2.0 + text_offset_top / 2.0).floor()
-            ).transform,
-            graphics
-        );
+        graphics::Text::new_color(color, text_size).draw(text,
+                                                         &mut cache.font,
+                                                         &context.draw_state,
+                                                         context.trans((x_pos + width / 2.0 -
+                                                                     text_width / 2.0)
+                                                                        .floor(),
+                                                                    (y_pos + height / 2.0 -
+                                                                     text_height / 2.0 +
+                                                                     text_offset_top / 2.0)
+                                                                        .floor())
+                                                             .transform,
+                                                         graphics);
```


```diff
-                        draw_text(
-                            [x_pos, y_pos, width, height],
-                            text,
-                            (height * 0.8) as u32,
-                            graphics::color::BLACK,
-                            cache, &context, graphics,
-                        );
+                        draw_text([x_pos, y_pos, width, height],
+                                  text,
+                                  (height * 0.8) as u32,
+                                  graphics::color::BLACK,
+                                  cache,
+                                  &context,
+                                  graphics);
```

```diff
-            graphics::Rectangle::new(graphics::color::WHITE).draw(
-                map.boundaries(),
-                &context.draw_state,
-                context.trans(screen_width / 2.0, screen_height / 2.0).flip_v().transform,
-                graphics,
-            );
-            graphics::image(
-                player.get_current_image(&cache.player),
-                context.trans(
-                    screen_width / 2.0 + player.state.absolute_x.ceil() + PLAYER_IMAGE_X_OFFSET as f64,
-                    screen_height / 2.0 - cache.player.get_height() as f64
-                        - player.state.absolute_y.ceil() - PLAYER_IMAGE_Y_OFFSET as f64
-                ).transform,
-                graphics,
-            );
+            graphics::Rectangle::new(graphics::color::WHITE).draw(map.boundaries(),
+                                                                  &context.draw_state,
+                                                                  context.trans(screen_width / 2.0,
+                                                                             screen_height / 2.0)
+                                                                      .flip_v()
+                                                                      .transform,
+                                                                  graphics);
+            graphics::image(player.get_current_image(&cache.player),
+                            context.trans(screen_width / 2.0 + player.state.absolute_x.ceil() +
+                                       PLAYER_IMAGE_X_OFFSET as f64,
+                                       screen_height / 2.0 - cache.player.get_height() as f64 -
+                                       player.state.absolute_y.ceil() -
+                                       PLAYER_IMAGE_Y_OFFSET as f64)
+                                .transform,
+                            graphics);
```

Hoping that isn't too many examples - this comes up a lot using piston's graphics crate which happens to have lots of parameters. Maybe I'm using it wrong, but I think the formatting I've used is more readable - in the function-within-function examples, it also helps a lot to clarify what arguments are going into what functions.

**Comment by topecongiro** [comment] 2017-07-10 08:35
Closing since the issue is fixed on the current master. We use block indent style for function call, and rustfmt now allows overflowing the last element of chain without splitting the entire chain.

**Closed by topecongiro** 2017-07-10 08:35 UTC
