### ISSUE TITLE
Comment in supertrait list causes line duplication

### ISSUE THREAD

**Issue by CAD97** [rust-lang-nursery/rustfmt#2166] opened 2017-11-19 05:42 UTC
[playground link](https://play.rust-lang.org/?gist=d241ef19b8fe7d045e37f01acd911092&version=stable)

```rust
use std::ops;

pub trait Slice
    : ops::Index<ops::Range<usize>, Output = Self>
    + ops::Index<ops::RangeFrom<usize>, Output = Self>
    + ops::Index<ops::RangeFull, Output = Self>
    + ops::Index<ops::RangeTo<usize>, Output = Self>
    // + ops::Index<ops::RangeInclusive<usize>, Output = Self>
    // + ops::Index<ops::RangeToInclusive<usize>, Output = Self>
    + ops::Index<ops::RangeTo<usize>, Output = Self> {
}
```

when formatted gives

```rust
use std::ops;

pub trait Slice
    : ops::Index<ops::Range<usize>, Output = Self>
    + ops::Index<ops::RangeFrom<usize>, Output = Self>
    + ops::Index<ops::RangeFull, Output = Self>
    + ops::Index<ops::RangeTo<usize>, Output = Self>
    + ops::Index<ops::RangeTo<usize>, Output = Self>
// + ops::Index<ops::RangeInclusive<usize>, Output = Self>
    // + ops::Index<ops::RangeToInclusive<usize>, Output = Self>
    + ops::Index<ops::RangeTo<usize>, Output = Self> {
}
```

Each subsequent format duplicates the line above the comment again.

**Comment by topecongiro** [comment] 2017-11-19 08:09
Thank you for filing an issue, I will close this as this is a duplicate of #2055.

**Closed by topecongiro** 2017-11-19 08:09 UTC
Labels: duplicate

**Comment by CAD97** [comment] 2017-11-19 08:16
My search has a long way to improve... I looked but did not find the preexisting report. Sorry for the dupe!
