### ISSUE TITLE
Rustfmt Usage Appveyor

### ISSUE THREAD

**Issue by ThomasdenH** [rust-lang-nursery/rustfmt#1561] opened 2017-05-17 10:19 UTC
I have an issue with testing my library on Appveyor using rustfmt. I use the command `cargo fmt -- --write-mode=diff` on both Travis and Appveyor. For some reason, this command has stopped working on Appveyor with the following error:
```
error: file not found for module `tests`
  --> \\?\C:\projects\iban-validate\src\lib.rs:54:5
   |
54 | mod tests;
   |     ^^^^^
   |
   = help: name the file either tests.rs or tests/mod.rs inside the directory "\\\\?\\C:\\projects\\iban-validate\\src"
```
When I remove the line for Appveyor, (keeping it in for Travis), the build succeeds. In the [diff](https://github.com/ThomasdenH/iban_validate/compare/1d1fcd9e1b80562a9e2702880960a94ca977fa95...af130dc9dccc3271b1ef4c037433c40cc177af48) you can see that really that line is the only change.

- [The failing build log](https://ci.appveyor.com/project/ThomasdenH/iban-validate/build/1.0.20) ([source](https://github.com/ThomasdenH/iban_validate/tree/1d1fcd9e1b80562a9e2702880960a94ca977fa95))
- [The working build](https://ci.appveyor.com/project/ThomasdenH/iban-validate/build/1.0.19) ([source](https://github.com/ThomasdenH/iban_validate/tree/af130dc9dccc3271b1ef4c037433c40cc177af48))

I am sorry if the issue turns out not to be related to rustfmt, but the reason I post it here is the following:
- A nearly identical build script works on Travis
- The directory that is missing really is there in both builds

**Comment by nrc** [comment] 2017-05-17 20:10
Can anyone reproduce this locally on Windows?

I'm not sure if this is possible, but is it possible to use the libsyntax branch on Appveyor and see if that works.

**Comment by dulanov** [comment] 2017-05-20 21:36
Yes, for me the same problem:

```
error: file not found for module `core`
  --> \\?\D:\Projects\emerald-rs\src\lib.rs:34:5
   |
34 | mod core;
   |     ^^^^
   |
   = help: name the file either core.rs or core/mod.rs inside the directory "\\\\?\\D:\\Projects\\emerald-rs\\src"
```

```
rustc 1.19.0-nightly (5dfcd85fd 2017-05-19)
binary: rustc
commit-hash: 5dfcd85fd4bae49445383baadf472fbdb414a0e6
commit-date: 2017-05-19
host: x86_64-pc-windows-msvc
release: 1.19.0-nightly
LLVM version: 4.0
```

```
> cargo fmt -- --version
0.8.4 ()
```

**Comment by dulanov** [comment] 2017-05-28 21:10
```
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<&str>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: syntex_syntax::parse::parser::Parser::default_submod_path
             at C:\Users\dulanov\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_syntax-0.58.1\src\parse\parser.rs:5317
   6: syntex_syntax::parse::parser::Parser::submod_path
             at C:\Users\dulanov\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_syntax-0.58.1\src\parse\parser.rs:5356
   7: syntex_syntax::parse::parser::Parser::parse_item_mod
             at C:\Users\dulanov\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_syntax-0.58.1\src\parse\parser.rs:5246
   8: syntex_syntax::parse::parser::Parser::parse_item_
             at C:\Users\dulanov\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_syntax-0.58.1\src\parse\parser.rs:5845
   9: syntex_syntax::parse::parser::Parser::parse_item
             at C:\Users\dulanov\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_syntax-0.58.1\src\parse\parser.rs:6023
  10: syntex_syntax::parse::parser::Parser::parse_mod_items
             at C:\Users\dulanov\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_syntax-0.58.1\src\parse\parser.rs:5192
  11: syntex_syntax::parse::parser::Parser::parse_crate_mod
             at C:\Users\dulanov\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_syntax-0.58.1\src\parse\parser.rs:6111
  12: rustfmt::parse_input
             at D:\Projects\rustfmt\src\lib.rs:550
  13: rustfmt::format_input<std::io::stdio::Stdout>
             at D:\Projects\rustfmt\src\lib.rs:592
  14: rustfmt::run
             at D:\Projects\rustfmt\src\lib.rs:653
  15: rustfmt::execute
             at D:\Projects\rustfmt\src\bin\rustfmt.rs:301
  16: rustfmt::main
             at D:\Projects\rustfmt\src\bin\rustfmt.rs:323
  17: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  18: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:52
  19: main
  20: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  21: BaseThreadInitThunk

```

**Comment by dulanov** [comment] 2017-05-28 21:35
Probably problem with `syntex_syntax`:

```

impl<'a> Parser<'a> {
    pub fn new(sess: &'a ParseSess,
               tokens: Vec<TokenTree>,
               directory: Option<Directory>,
               desugar_doc_comments: bool)
               -> Self {
        let tt = TokenTree::Delimited(syntax_pos::DUMMY_SP, Rc::new(Delimited {
            delim: token::NoDelim,
            tts: tokens,
        }));
        let mut parser = Parser {
            sess: sess,
            token: token::Underscore,
            span: syntax_pos::DUMMY_SP,
            prev_span: syntax_pos::DUMMY_SP,
            prev_token_kind: PrevTokenKind::Other,
            restrictions: Restrictions::empty(),
            quote_depth: 0,
            parsing_token_tree: false,
            obsolete_set: HashSet::new(),
            directory: Directory { path: PathBuf::new(), ownership: DirectoryOwnership::Owned },
            root_module_name: None,
            expected_tokens: Vec::new(),
            tts: if tt.len() > 0 { vec![(tt, 0)] } else { Vec::new() },
            desugar_doc_comments: desugar_doc_comments,
            cfg_mods: true,
        };

        let tok = parser.next_tok();
        parser.token = tok.tok;
        parser.span = tok.sp;
        if let Some(directory) = directory {
            parser.directory = directory;
        } else if parser.span != syntax_pos::DUMMY_SP {
            parser.directory.path = PathBuf::from(sess.codemap().span_to_filename(parser.span));
            parser.directory.path.pop();
            println!(">>> {:?}", parser.directory.path);
        }
        parser
    }
```

`>>> "\\\\?\\D:\\Projects\\emerald-rs\\src"`

**Comment by dulanov** [comment] 2017-05-28 22:37
I reproduced it, that bug came with - https://github.com/rust-lang-nursery/rustfmt/commit/c5f07eda4157aa34a9b882029ab7754f9a7a755f

**Comment by dulanov** [comment] 2017-05-28 22:47
Probably this issue related to https://github.com/rust-lang/rust/issues/27706

**Comment by dulanov** [comment] 2017-05-28 23:12
The main probem with https://github.com/rust-lang-nursery/rustfmt/commit/c5f07eda4157aa34a9b882029ab7754f9a7a755f is `std::fs::metadata` return false for `std::fs::canonicalize` on Windows?

**Comment by nrc** [comment] 2017-05-28 23:39
According to the docs both `canonicalize` and `metadata` have Windows-specific implementations, so it seems weird that either would not work work. AFAICT from the Rust issues, it looks like the Windows issues were resovled before stabilisation?

@dulanov could try reproducing with the libsyntax branch please? That does not use Syntex, so it might eliminate some causes of the error.

**Comment by dulanov** [comment] 2017-05-29 00:04
For `libsyntax`:

`cargo build`, `cargo test`, `cargo build --release` > `ok`, but

```> RUST_BACKTRACE=1 ../rustfmt/target/debug/cargo-fmt.exe
D:/Projects/rustfmt/target/debug/cargo-fmt.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by nrc** [comment] 2017-05-29 20:40
@dulanov I think you need to add the directory with the Rust DLLs to your PATH variable. (Or copy the dlls to the working directory). I'm not 100% sure on this because I'm not very familiar with Windows.

**Comment by dulanov** [comment] 2017-05-29 20:51
@nrc normally `C:\Windows\SysWOW64` but I firstly try the same directory.

**Comment by dulanov** [comment] 2017-05-29 20:58
hm, with copied in `target/release` rust dlls it works.

**Comment by dulanov** [comment] 2017-05-29 21:06
yes, it works with copied dlls into `target/release`.

**Comment by nrc** [comment] 2017-05-29 21:17
@dulanov awesome, thanks for checking this.

I think this means that it will be fixed when we move the main branch to being libsyntax.

**Comment by dulanov** [comment] 2017-05-29 21:21
Great, thanks a lot, but anyway, a fix workaround for current version who need it now:

1. `git checkout tags/0.8.4`
2. revert changes from https://github.com/rust-lang-nursery/rustfmt/commit/c5f07eda4157aa34a9b882029ab7754f9a7a755f
3. `cargo install --force`

**Comment by ThomasdenH** [comment] 2017-05-30 06:16
Great, thank you both!

**Closed** 2017-09-10 11:19 UTC
Labels: bug
