### ISSUE TITLE
Comments in functions being indented badly

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#653] opened 2015-11-23 23:04 UTC
e.g.,
```
     fn test_rng_true_values() {
-        // Test vectors 1 and 2 from
-        // http://tools.ietf.org/html/draft-nir-cfrg-chacha20-poly1305-04
+    // Test vectors 1 and 2 from
+    // http://tools.ietf.org/html/draft-nir-cfrg-chacha20-poly1305-04
 ```

**Comment by nrc** [comment] 2015-11-23 23:07
Also in impls

**Comment by marcusklaas** [comment] 2015-11-24 20:44
I have an idea about what may have caused this.

**Comment by marcusklaas** [comment] 2015-11-24 20:53
@nrc, I can't reproduce easily. Can you provide a more complete example?
```rust
fn main() {
    fn test() {
        // comment
    }
}
```
is unchanged by rustfmt atm..

**Comment by nrc** [comment] 2015-11-24 21:10
I'll try and figure something out, in the mean time, the source I was reformatting is here: https://dxr.mozilla.org/rust/source/src/librand/chacha.rs#249

**Comment by marcusklaas** [comment] 2015-11-30 22:08
This happens for skipped items. Closing in favour of https://github.com/rust-lang-nursery/rustfmt/issues/661.

**Closed by marcusklaas** 2015-11-30 22:08 UTC
Labels: comments, p-high, poor-formatting
