### ISSUE TITLE
Backup files should only be created if the file changed

### ISSUE THREAD

**Issue by skylerberg** [rust-lang-nursery/rustfmt#789] opened 2016-01-30 19:13 UTC
It may be intentional the way it is, if so please let me know why and close this. Otherwise, I think that there should only be *.bk files for changed files. Right now it is kind of annoying to always have to cleanup a pile of backup files even when nothing changed.

**Comment by marcusklaas** [comment] 2016-01-31 10:30
I believe this was fixed by https://github.com/rust-lang-nursery/rustfmt/pull/740. Have we regressed here?

**Comment by Amanieu** [comment] 2016-02-23 20:54
Yes there has been a regression, it seems `.bk` files are being generated even if the files do not change.

**Comment by nrc** [comment] 2016-03-14 05:24
I can't reproduce this with current rustfmt.

@skylerberg, @Amanieu are you able to repro with a current master? Could you post exactly how (flags, non-default config options, project structure)? Thanks!

**Comment by skylerberg** [comment] 2016-03-14 05:59
The easiest why that I can repro this is using this repo: https://github.com/redox-os/ion. I go to the `src` folder and run `rustfmt to_num.rs`. Nothing changes, but a file `to_num.rs.bk` is produced. I just downloaded the and built from the latest master, so `rustfmt` should be up to date. I did nothing to configure it.

I am running on Ubuntu 14.04.

**Comment by nrc** [comment] 2016-05-17 23:36
I tried again to repro this and could not, so closing for now. Happy to re-open if we can find a way to repro.

**Closed by nrc** 2016-05-17 23:36 UTC
Labels: p-high
