### ISSUE TITLE
called `Result::unwrap()` on an `Err` value + ICE (panicked while panicking) + Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by respeccing** [rust-lang-nursery/rustfmt#900] opened 2016-04-03 10:59 UTC
```bash
$ time echo 'd'|RUST_BACKTRACE=1 ./rustfmt
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "expected item, found `d`"', src/libcore/result.rs:746
stack backtrace:
   1:     0x55c225ab60b0 - std::sys::backtrace::tracing::imp::write::h3152d690c5b90b0c
   2:     0x55c225ab8bfb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hb638acea7c29901b
   3:     0x55c225ab8882 - std::panicking::default_hook::h508c3dab3df347d6
   4:     0x55c225aaa0ef - std::sys_common::unwind::begin_unwind_inner::h5cd31b1580026517
   5:     0x55c225aab2a8 - std::sys_common::unwind::begin_unwind_fmt::h5d8ad4b339509f9d
   6:     0x55c225ab5591 - rust_begin_unwind
   7:     0x55c225b01f4f - core::panicking::panic_fmt::h813eaa27a5810609
   8:     0x55c2255a7070 - core::result::unwrap_failed::h0e74a4dec4fa7a73
                        at src/libcore/macros.rs:29
   9:     0x55c22559d960 - _<std..result..Result<T, E>>::unwrap::h4bf802c90315c099
                        at src/libcore/result.rs:687
  10:     0x55c22559a4b5 - rustfmt::format_string::h2082095943e74a1c
                        at src/lib.rs:381
  11:     0x55c2255b8b3b - rustfmt::run_from_stdin::h1e8135c29ff2a697
                        at src/lib.rs:445
  12:     0x55c2255582b6 - rustfmt::execute::h9c9253d20e08b170
                        at src/bin/rustfmt.rs:200
  13:     0x55c22556a3cc - rustfmt::main::h72bee7f7a14fa8c0
                        at src/bin/rustfmt.rs:245
  14:     0x55c225ab84b4 - std::sys_common::unwind::try::try_fn::h48f26a76fbfde40e
  15:     0x55c225ab551b - __rust_try
  16:     0x55c225ab7efb - std::rt::lang_start::h7bd5d5e5d238827f
  17:     0x55c22556bb69 - main
  18:     0x7f84eee1e59f - __libc_start_main
  19:     0x55c225552768 - _start
  20:                0x0 - <unknown>
error: internal compiler error: Error constructed but not emitted
thread '<main>' panicked at 'explicit panic', /home/zazdxscf/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.30.0/src/errors/mod.rs:360
stack backtrace:
   1:     0x55c225ab60b0 - std::sys::backtrace::tracing::imp::write::h3152d690c5b90b0c
   2:     0x55c225ab8bfb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hb638acea7c29901b
   3:     0x55c225ab8882 - std::panicking::default_hook::h508c3dab3df347d6
   4:     0x55c225aaa0ef - std::sys_common::unwind::begin_unwind_inner::h5cd31b1580026517
   5:     0x55c225770a67 - std::sys_common::unwind::begin_unwind::h422885d31fe250dc
                        at src/libstd/sys/common/unwind/mod.rs:219
   6:     0x55c225786c9a - _<errors..DiagnosticBuilder<'a> as std..ops..Drop>::drop::h7f3aa5f2eda70e5a
                        at /home/zazdxscf/build/1nonpkgs/rustfmt/<std macros>:3
   7:     0x55c2255a70bc - syntax..errors..DiagnosticBuilder<'static>::drop.26437::h8b5708f1ad38063e
   8:     0x55c2255a7015 - core::result::unwrap_failed::h0e74a4dec4fa7a73
                        at src/libcore/result.rs:745
   9:     0x55c22559d960 - _<std..result..Result<T, E>>::unwrap::h4bf802c90315c099
                        at src/libcore/result.rs:687
  10:     0x55c22559a4b5 - rustfmt::format_string::h2082095943e74a1c
                        at src/lib.rs:381
  11:     0x55c2255b8b3b - rustfmt::run_from_stdin::h1e8135c29ff2a697
                        at src/lib.rs:445
  12:     0x55c2255582b6 - rustfmt::execute::h9c9253d20e08b170
                        at src/bin/rustfmt.rs:200
  13:     0x55c22556a3cc - rustfmt::main::h72bee7f7a14fa8c0
                        at src/bin/rustfmt.rs:245
  14:     0x55c225ab84b4 - std::sys_common::unwind::try::try_fn::h48f26a76fbfde40e
  15:     0x55c225ab551b - __rust_try
  16:     0x55c225ab7efb - std::rt::lang_start::h7bd5d5e5d238827f
  17:     0x55c22556bb69 - main
  18:     0x7f84eee1e59f - __libc_start_main
  19:     0x55c225552768 - _start
  20:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)

real	0m1.341s
user	0m1.102s
sys	0m0.185s
```
(this eats CPU without returning, if ran inside a virtualbox-ed Manjaro(ArchLinux-like);
but on gentoo above returned with core dump)

rustfmt commit tested: d9ccec6f82fb4d58e41b78de6be530de72e4db00

$ rustc -Vv
!! executing '/home/zazdxscf/build/1nonpkgs/rust/rust//x86_64-unknown-linux-gnu/stage2/bin//rustc' with args: '-Vv'
rustc 1.9.0-dev (f2285bdaf 2016-04-02)
binary: rustc
commit-hash: f2285bdaf57e9cb56120902ae4b3b0a26d761f31
commit-date: 2016-04-02
host: x86_64-unknown-linux-gnu
release: 1.9.0-dev

(the virtualboxed rustc version was:
\# rustc -Vv
rustc 1.9.0-nightly (c8b8eb1fd 2016-04-01)
binary: rustc
commit-hash: c8b8eb1fda90998832ba1cdf96a34dc676f7124b
commit-date: 2016-04-01
host: x86_64-unknown-linux-gnu
release: 1.9.0-nightly
)

**Comment by nrc** [comment] 2016-04-08 03:53
@respeccing do you have a test case for generating this error? (It may have been fixed by a recent PR).

**Comment by respeccing** [comment] 2016-04-08 08:15
did this not work? ;-)
`echo 'd'|RUST_BACKTRACE=1 ./rustfmt`
I'll try it again and edit this comment with the result

**Comment by marcusklaas** [comment] 2016-04-15 16:14
I can't reproduce this. I'm getting
```
marcusklaas@marcusklaas ~/rustfmt> echo 'd' | env RUST_BACKTRACE=1 target/debug/rustfmt
stdin:1:1: 1:2 error: expected item, found `d`
stdin:1 d
        ^
```
. No ICE.

**Comment by marcusklaas** [comment] 2016-04-15 16:16
This has probably been fixed. If this still persists for some environments, we'll reopen.

**Closed by marcusklaas** 2016-04-15 16:16 UTC
Labels: bug
