### ISSUE TITLE
Issue with comment in use statement

### ISSUE THREAD

**Issue by philipper905** [rust-lang-nursery/rustfmt#2934] opened 2018-08-18 01:46 UTC
When I have this
```
use std::{
    // cell::RefCell,
    ops::{Index, IndexMut},
    rc::Rc,
};
```
Rustfmt will convert the file to this:
```
use std::{
    // cell::RefCell, ops::{Index, IndexMut},
    rc::Rc,
};
```
Which means that second line is also commented out.
This isn't really much of a problem in practice but just wanted to alert in case it was a unknown issue.

**Comment by crw5996** [comment] 2018-08-20 19:27
I was unable to reproduce this error with the information given. I cloned and built rustfmt used the following program...  
```
use std::{
    // cell::RefCell,
    ops::{Index, IndexMut},
    rc::Rc,
};

fn main() {
    println!("HELLO WORLD!");
}
```
and the resulting file was exactly the same after running rustfmt on the file. I'm curious if I am missing something?

**Comment by nrc** [comment] 2018-08-22 03:17
This might be fixed on master, but not on nightly?

**Comment by philipper905** [comment] 2018-08-23 17:31
yeah, it works correctly on master.

**Closed** 2018-08-23 17:31 UTC
Labels: bug, comments, poor-formatting
