### ISSUE TITLE
Some files in tests/target/ don't exist in tests/source/

### ISSUE THREAD

**Issue by eefriedman** [rust-lang-nursery/rustfmt#394] opened 2015-09-28 02:03 UTC
Easy way to improve test coverage: add a bunch of corresponding files to source/ .

```
@@ -1,10 +1,14 @@
 assignment.rs
+attrib-extern-crate.rs
 attrib.rs
 chains-no-overflow.rs
+chains-no-overlow-2.rs
 chains.rs
 closure.rs
+comments-fn.rs
 doc.rs
 empty_file.rs
+enum.rs
 expr-no-hints.rs
 expr.rs
 extern.rs
@@ -14,14 +18,17 @@
 fn-custom-5.rs
 fn-custom-6.rs
 fn-custom.rs
+fn.rs
 fn-simple.rs
 hard-tabs.rs
-hello2.rs
 hello.rs
 imports-reorder.rs
 imports.rs
+issue-64.rs
+long-fn-1.rs
 loop.rs
 macros.rs
+match.rs
 mod-1.rs
 mod-2.rs
 multiple.rs
@@ -30,9 +37,13 @@
 other.rs
 paths.rs
 single-line-if-else.rs
+skip.rs
+string-lit-custom.rs
 string-lit.rs
 struct_lits_multiline.rs
 struct_lits.rs
 struct_lits_visual_multiline.rs
 struct_lits_visual.rs
 structs.rs
+trait.rs
+tuple.rs
```

**Comment by nrc** [comment] 2015-09-28 02:06
This is somewhat by design - they are designed to be used for idempotent tests.

It would be pretty easy to make source->target tests by taking the target files and removing (nearly) all whitespace. The hard bit is then undoing this where we aren't perfect yet.

**Comment by marcusklaas** [comment] 2016-04-14 15:58
I'll close this since this was intentional as @nrc mentioned.

**Closed by marcusklaas** 2016-04-14 15:58 UTC
Labels: easy
