### ISSUE TITLE
Inconsistent behavior 

### ISSUE THREAD

**Issue by volzkzg** [rust-lang-nursery/rustfmt#2716] opened 2018-05-18 06:04 UTC
The problem is as following. 

When I run `cargo fmt --all`, it should modify all the files that do not follow the format standard. But after I running `cargo fmt --all -- --check`, it still tells me one file does not have the correct format.

```
root@d115673865b5:~/cita# cargo fmt --all
root@d115673865b5:~/cita# cargo fmt --all -- --check
Diff in /root/cita/tools/relayer-parser/src/communication.rs at line 126:
         define_reply_type!(ReplyType, $result_type);
         let rpc_cli = RpcClient::new($upstream);
         let body: String = json!({
-                                    "jsonrpc": "2.0",
-                                    "method": $method,
-                                    "params": json!($params),
-                                    "id": 1
-                                }).to_string();
+                                        "jsonrpc": "2.0",
+                                        "method": $method,
+                                        "params": json!($params),
+                                        "id": 1
+                                    }).to_string();
         let data = rpc_cli.do_post(&body)?;
         let reply: ReplyType = serde_json::from_slice(&data).map_err(|_| {
             error!(

```

Rustfmt version is `nightly-2018-05-17`
System is `Ubuntu 18.04`

**Comment by nrc** [comment] 2018-05-18 06:17
If you run `cargo fmt` twice, does the second run reformat?

**Comment by volzkzg** [comment] 2018-05-19 10:35
@nrc I investigate this bug a little bit today. Here is my observations. 

Suppose we have same snippet 
```
let body: String = json!({
"jsonrpc": "2.0",
"method": $method,
"params": json!($params),
"id": 1})
.to_string();
```
in two blocks, the one is inside macro declaration and the another is in main function. (i.e, I guess we have different approach to macro and function).

It will look like this 
```
macro_rules! rpc_send_and_get_result_from_reply {
    ($upstream:ident, $method:expr, $params:tt, $result_type:path) => {{
        define_reply_type!(ReplyType, $result_type);
        let rpc_cli = RpcClient::new($upstream);

        let body: String = json!({
        "jsonrpc": "2.0",
        "method": $method,
        "params": json!($params),
        "id": 1})
        .to_string();

        let data = rpc_cli.do_post(&body)?;
        let reply: ReplyType = serde_json::from_slice(&data).map_err(|_| {
            error!(
                "send {:?} return error: {:?}",
                &body,
                ::std::str::from_utf8(&data)
            );
            Error::Parse
        })?;
        trace!("get reply {:?}.", reply);
        reply.result
    }};
}

fn main() {
    let body: String = json!({
    "jsonrpc": "2.0",
    "method": $method,
    "params": json!($params),
    "id": 1})
    .to_string();
}
```

When I try `cargo fmt -- --check```, the information is following

```
root@d115673865b5:~/format# cargo fmt -- --check
Diff in /root/format/src/main.rs at line 2:
     ($upstream:ident, $method:expr, $params:tt, $result_type:path) => {{
         define_reply_type!(ReplyType, $result_type);
         let rpc_cli = RpcClient::new($upstream);
-
+
         let body: String = json!({
-        "jsonrpc": "2.0",
-        "method": $method,
-        "params": json!($params),
-        "id": 1})
-        .to_string();
-
+            "jsonrpc": "2.0",
+            "method": $method,
+            "params": json!($params),
+            "id": 1})
+            .to_string();
+
         let data = rpc_cli.do_post(&body)?;
         let reply: ReplyType = serde_json::from_slice(&data).map_err(|_| {
             error!(
Diff in /root/format/src/main.rs at line 30:
     "method": $method,
     "params": json!($params),
     "id": 1})
-    .to_string();
+        .to_string();
 }
```

We found two different approach to deal with this json! macro. 

1. The one in main function just ignore any indentation for arguments inside json! macro. 
2. The one in macros indent all arguments inside json!() by 4 spaces and .to_string() by 4 spaces too.

**Comment by nrc** [comment] 2018-05-20 20:05
THanks for the additional info! Will try and fix this soon...

**Comment by topecongiro** [comment] 2018-05-23 13:51
This seems to be a duplicate of #2695.

**Comment by volzkzg** [comment] 2018-05-23 14:40
@topecongiro I'm not sure, because the version of my rustfmt is 2018-05-17. And they said their issue was fixed in the newest nightly 11 days ago.

**Comment by topecongiro** [comment] 2018-06-15 01:44
I think the issue is already fixed on the master (via #2775). We need to add regression tests to close this issue.

**Comment by okready** [comment] 2018-06-15 02:06
Just installed the latest from `master`. I can verify that the issue does not occur when running it on my test case or the code from which it was based. Thanks!

**Comment by okready** [comment] 2018-06-15 04:48
I was looking into adding a regression test, but it appears this is the same bug as #2607, which has a regression test (even the workaround mentioned in that bug to use curly braces instead of parentheses bypasses the issue with older versions of `rustfmt`). Should this just be marked a a duplicate, or should there still be similar tests using the code examples from this issue?

**Comment by scampi** [comment] 2018-06-23 12:47
@nrc should this issue be closed ?

**Closed** 2018-06-24 20:52 UTC
Labels: bug, good-first-issue, macros
