### ISSUE TITLE
Adds trailing whitespaces to code blocks in doc comments and then complains about it

### ISSUE THREAD

**Issue by vorner** [rust-lang-nursery/rustfmt#2260] opened 2017-12-10 08:53 UTC
Hello

I have an example in doc comment and separate parts of the code by empty lines. I don't have trailing whitespace on the empty lines.

However, rustfmt tries to add them and then complains about them there. Even the complaint is a bit wrong, because it didn't merely *leave* them there, it *added* them. I believe both is wrong.

```diff
Diff in /home/vorner/prog/slog-retry/src/lib.rs at line 29:
 //! extern crate slog_async;⏎
 //! extern crate slog_json;⏎
 //! extern crate slog_retry;⏎
-//!⏎
+//! ⏎
 //! use std::net::TcpStream;⏎
-//!⏎
+//! ⏎
 //! use slog::Drain;⏎
-//!⏎
+//! ⏎
 //! fn main() {⏎
 //!     let retry = slog_retry::Retry::new(|| -> Result<_, std::io::Error> {⏎
 //!             let connection = TcpStream::connect("127.0.0.1:1234")?;⏎
```

```
error: left behind trailing whitespace
  --> /home/vorner/prog/slog-retry/src/lib.rs:32
   |
32 | //! 
   |    ^

error: left behind trailing whitespace
  --> /home/vorner/prog/slog-retry/src/lib.rs:34
   |
34 | //! 
   |    ^

error: left behind trailing whitespace
  --> /home/vorner/prog/slog-retry/src/lib.rs:36
   |
36 | //! 
   |    ^
```

**Comment by topecongiro** [comment] 2017-12-10 09:23
Would you tell us which version of rustfmt you are using? I think this is fixed on the latest version.

**Comment by vorner** [comment] 2017-12-10 10:40
Oh, sorry, I forgot. It's whatever I got this morning out of rustup.

```
0.2.17-nightly (ae51f69 2017-12-05)
```

Is it possible the latest version didn't get there yet?

**Comment by topecongiro** [comment] 2017-12-10 12:19
Thanks, though I could not reproduce this with the default setting. Would you show us the config options you were using?

**Comment by vorner** [comment] 2017-12-10 15:48
The complete repository where I get this, including the config is here: https://github.com/vorner/slog-retry (the config is https://github.com/vorner/slog-retry/blob/master/rustfmt.toml, I know it's long, but I mostly just edited the default config, but I might have some options from earlier versions).

**Comment by topecongiro** [comment] 2017-12-11 02:35
Thank you, I could reproduce this. The relevant option was `wrap_comments = true`.

**Closed** 2017-12-11 03:40 UTC
Labels: bug, comments, only-with-option

**Comment by vorner** [comment] 2017-12-11 06:27
Thank you. As usual, I'm amazed by the incredible speed people around Rust fix things :-).
