### ISSUE TITLE
Rustfmt bail out on broken files

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#1073] opened 2016-06-20 09:56 UTC
If a file doesn't compile (e.g. because it has errors) in my experience rustfmt has an extremely high chance of getting an internal error. 

Cargo fmt should probably verify that a file compiles (or has just been compiled) before throwing it to rustfmt, but maybe rustfmt should check if a file parses/type-checks properly before trying to format it as well.

**Comment by nrc** [comment] 2016-06-20 20:14
This behaviour shouldn't happen any more, it should have been fixed. Do you have an example where it still happens? And is it with master or the current published version?

**Comment by gnzlbg** [comment] 2016-06-21 09:29
It is with the 0.5.0 version (should be the currently released one). I'll try to come up with a minimal example but that might take a bit since rustfmt started erroring on my crate yesterday afternoon and gotta fix that first.

**Comment by topecongiro** [comment] 2017-05-28 04:26
Closing since the issue is not reproduced on the current master.

**Closed by topecongiro** 2017-05-28 04:26 UTC
Labels: bug
