### ISSUE TITLE
Comment is removed on formatting

### ISSUE THREAD

**Issue by TRox1972** [rust-lang-nursery/rustfmt#1748] opened 2017-06-25 15:33 UTC
When `rustfmt` is run [this code](https://play.rust-lang.org/?gist=a3f03ac5314fb27c52f9134845effc76&version=stable&backtrace=0) (from chapter 3.19 Traits in the first edition of "The Rust Programming Language"), the last comment is removed.

**Comment by topecongiro** [comment] 2017-06-25 22:36
I will close this issue since this is a duplicate of #458.

**Closed by topecongiro** 2017-06-25 22:36 UTC
Labels: bug, comments, duplicate
