### ISSUE TITLE
Rustfmt fails in raw string literals with trailing whitespace 

### ISSUE THREAD

**Issue by overvenus** [rust-lang-nursery/rustfmt#1317] opened 2017-02-15 06:56 UTC
```rust
fn main() {
    let a = r#"
A line with trailing whitespace    
"#;

    println!("{}", a);
}
```

Rustfmt fails with the following error:
`Rustfmt failed at foo.rs:3: left behind trailing whitespace (sorry)`

I would expect that rustfmt doesn't complain about trailing whitespace in raw string literals. Because they were deliberately placed there.

**Comment by topecongiro** [comment] 2017-05-14 07:03
Closing since this is a duplicate of #1220.

**Closed by topecongiro** 2017-05-14 07:03 UTC
