### ISSUE TITLE
opening brace moved up when impl for spans multiple lines

### ISSUE THREAD

**Issue by tspiteri** [rust-lang-nursery/rustfmt#2491] opened 2018-02-26 11:39 UTC
Current git produces:
```rust
impl<'a, 'b, 'c> ThisIsFine<Something>
    for (&'a mut Something, &'b mut Something, &'c mut Something)
{
    fn foo() {}
}
impl<'a, 'b, 'c> ThisIsBad<Something>
    for (
        &'a mut SomethingLong,
        &'b mut SomethingLong,
        &'c mut SomethingLong,
    ) {
    fn foo() {}
}
```
I would expect the opening brace of the second impl to be on a new line like in the first impl.

**Comment by nrc** [comment] 2018-03-01 19:18
> I would expect the opening brace of the second impl to be on a new line like in the first impl.

Agree

**Comment by topecongiro** [comment] 2018-03-05 15:49
I thought that this is an expected behavior. rustfmt does this kind of compressing the closing paren and the opening brace in other places as well. For example, in `if` expression,

```rust
if foo(
    xxxxxxxxxxxxxxxxxxxxxxx,
    yyyyyyyyyyyyyyyyyyyyyyy,
    zzzzzzzzzzzzzzzzzzzzzzzzzz,
) {
    println!("hello, world");
}
```

instead of

```rust
if foo(
    xxxxxxxxxxxxxxxxxxxxxxx,
    yyyyyyyyyyyyyyyyyyyyyyy,
    zzzzzzzzzzzzzzzzzzzzzzzzzz,
)
{
    println!("hello, world");
}
```

**Comment by topecongiro** [comment] 2018-03-05 15:51
I think in this case it looks a bit weird because `for` is indented.

**Comment by tspiteri** [comment] 2018-03-05 16:01
I don't think it should be intended behaviour. I think the behaviour should depend on the answer to this question: If `)` is on the same line as its matching `(`, would `{` be on the same line?

If the answer to the question is yes, as in:
```rust
if foo(x, y, z) {
```
then the `{` should be kept on the same line as `)`, as in:
```rust
if foo(
    xxxxxxxxxxxxxxxxxxxxxxx,
    yyyyyyyyyyyyyyyyyyyyyyy,
    zzzzzzzzzzzzzzzzzzzzzzzzzz,
) {
```

But if the answer is no, as in:
```rust
impl<'a, 'b, 'c> ThisIsFine<Something>
    for (&'a mut Something, &'b mut Something, &'c mut Something)
{
```
then the `{` should be on a new line, as in
```rust
impl<'a, 'b, 'c> ThisIsBad<Something>
    for (
        &'a mut SomethingLong,
        &'b mut SomethingLong,
        &'c mut SomethingLong,
    )
{
```

Conversely, this is bad:
```rust
if foo(x, y, z)
{
```
so this is bad:
```rust
if foo(
    xxxxxxxxxxxxxxxxxxxxxxx,
    yyyyyyyyyyyyyyyyyyyyyyy,
    zzzzzzzzzzzzzzzzzzzzzzzzzz,
)
{
```

And this is bad:
```rust
impl<'a, 'b, 'c> ThisIsFine<Something>
    for (&'a mut Something, &'b mut Something, &'c mut Something) {
```
so this should be bad too:
```rust
impl<'a, 'b, 'c> ThisIsBad<Something>
    for (
        &'a mut SomethingLong,
        &'b mut SomethingLong,
        &'c mut SomethingLong,
    ) {
```

**Comment by tspiteri** [comment] 2018-03-05 16:04
In other words, if rustfmt splits `( /* ... */ )` into multiple lines, that should not pull an opening brace `{` from the next line to go with the closing bracket `)`.

**Comment by topecongiro** [comment] 2018-03-05 16:10
@tspiteri That is a good point, thank you for clarifying! I am convinced that the current behavior is bad.

**Closed** 2018-03-09 02:15 UTC
Labels: poor-formatting
