### ISSUE TITLE
rustfmt compilation hangs on nightly (f4209651e 2017-05-05)

### ISSUE THREAD

**Issue by mottalli** [rust-lang-nursery/rustfmt#1517] opened 2017-05-08 15:30 UTC
Not sure if this belongs here, but I've tried to install rustfmt via `cargo install rustfmt` on two different architectures (amd64 and armv7) and in both cases the compilation hangs when it tries to compile the `env_logger` crate.

The output of the command is:

```bash
$ rustup update
info: syncing channel updates for 'nightly-armv7-unknown-linux-gnueabihf'
info: checking for self-updates

  nightly-armv7-unknown-linux-gnueabihf unchanged - rustc 1.19.0-nightly (f4209651e 2017-05-05)

$ cargo install rustfmt                                                   
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing rustfmt v0.8.3
   Compiling unicode-xid v0.0.4
   Compiling unicode-segmentation v1.1.0
   Compiling libc v0.2.22
   Compiling multimap v0.3.0
   Compiling bitflags v0.8.2
   Compiling void v1.0.2
   Compiling diff v0.1.10
   Compiling unreachable v0.1.1
   Compiling utf8-ranges v1.0.0
   Compiling log v0.3.7
   Compiling thread-id v3.0.0
   Compiling thread_local v0.3.3
   Compiling rustc-serialize v0.3.24
   Compiling regex-syntax v0.4.0
   Compiling getopts v0.2.14
   Compiling either v1.1.0
   Compiling itertools v0.5.10
   Compiling strings v0.0.1
   Compiling memchr v1.0.1
   Compiling aho-corasick v0.6.3
   Compiling same-file v0.1.3
   Compiling walkdir v1.0.7
   Compiling term v0.4.5
   Compiling rustfmt v0.8.3
   Compiling regex v0.2.1
   Compiling toml v0.2.1
   Compiling syntex_pos v0.58.1
   Compiling syntex_errors v0.58.1
   Compiling syntex_syntax v0.58.1
   Compiling env_logger v0.4.2
# Halts indefinitely, uses 100% of 1 CPU
```

Again, the exact same thing happened on an amd64 architecture. I'm guessing this may be a compiler error so please let me know if I should report it somewhere else.

**Comment by nrc** [comment] 2017-05-08 18:37
This is probably hanging on one of the larger syntex_* crates, not env_logger, it looks like env_logger because Cargo compiles crates in parallel where possible. I presume this is a compiler bug. Will investigate.

**Comment by nrc** [comment] 2017-05-08 18:47
I reported this here: https://github.com/rust-lang/rust/issues/41832 I couldn't reproduce locally. Closing this issue since it should be investigated on the Rust repo.

**Closed by nrc** 2017-05-08 18:47 UTC
