### ISSUE TITLE
'match_pattern_separator_break_point' appears to have no effect

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang-nursery/rustfmt#1952] opened 2017-09-09 08:12 UTC
In my `rustfmt.toml`, I have `match_pattern_separator_break_point = "Front"`. However, running `rustfmt` with this option results in the following:

```diff
-                Outcome::Success(_) | Outcome::Failure(_) => return outcome,⏎
+                Outcome::Success(_) |⏎
+                Outcome::Failure(_) => return outcome,⏎
```

First, I would expect the diff to be empty since the full pattern is within `max_width`, so making any change here seems incorrect. But, if the pattern did need to be split, the separator should be placed in the front, not back, as specified in `match_pattern_separator_break_point`.

Finally, on a related note, there's doesn't appear to be a way to control the spacing between a binder ident and a pattern: `ident @ pattern`. This results in the following:

```diff
             match outcome {⏎
-                o@Outcome::Success(_) | o@Outcome::Failure(_) => return o,⏎
+                o @ Outcome::Success(_) |⏎
+                o @ Outcome::Failure(_) => return o,⏎
                 Outcome::Forward(unused_data) => data = unused_data,⏎
             };⏎
```

**Comment by SergioBenitez** [comment] 2017-09-09 08:58
#1807 and https://github.com/rust-lang-nursery/fmt-rfcs/issues/34 are related.

**Comment by topecongiro** [comment] 2017-09-09 13:41
Could you please give us the version of rustfmt you used and your whole rustfmt.toml?
I could not reproduce this with `0.2.5-nightly ()` and just setting `match_pattern_separator_break_point = "Front"`.

**Comment by nrc** [comment] 2017-09-18 04:06
Assume this is fixed on latest nightly. Closing (please comment if this is not fixed and I'll re-open)

**Closed by nrc** 2017-09-18 04:06 UTC
