### ISSUE TITLE
Unexpected newline in empty impl

### ISSUE THREAD

**Issue by Wilfred** [rust-lang-nursery/rustfmt#670] opened 2015-12-03 21:32 UTC
Given the code:

```rust
impl<I> MapLoopsExt for I where I: Iterator<Item=Instruction> { }
```

Rustfmt produces:

```rust
impl<I> MapLoopsExt for I where I: Iterator<Item = Instruction>
{}
```

I think it'd be tidier to leave the `{}` on the same line.

**Comment by marcusklaas** [comment] 2015-12-04 15:35
Dupe of https://github.com/rust-lang-nursery/rustfmt/issues/650.

**Closed by marcusklaas** 2015-12-04 15:35 UTC
