### ISSUE TITLE
Multiline single string argument formatted strangely

### ISSUE THREAD

**Issue by sgrif** [rust-lang-nursery/rustfmt#1716] opened 2017-06-17 16:41 UTC
Unsure if this is a bug or an intentional part of the RFC style, but this case stood out to me from running it against Diesel:

```patch

 fn create_schema_migrations_table_if_needed<Conn: Connection>(conn: &Conn) -> QueryResult<usize> {
     conn.silence_notices(|| {
-        conn.execute("CREATE TABLE IF NOT EXISTS __diesel_schema_migrations (
+        conn.execute(
+            "CREATE TABLE IF NOT EXISTS __diesel_schema_migrations (
             version VARCHAR(50) PRIMARY KEY NOT NULL,
             run_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-        )")
+        )",
+        )
     })
```

**Comment by topecongiro** [comment] 2017-06-17 17:08
Closing since this is a duplicate of #1661.

**Comment by topecongiro** [comment] 2017-06-18 13:18
This is actually slightly different from #1661, since aligning the string changes the behaviour.

**Comment by nrc** [comment] 2018-06-24 23:33
I think this is sort of intentional - a side effect of rustfmt being happy to move the start of strings but not insert whitespace into strings. I think the fix is to manually indent the 2nd, 3rd, and 4th lines of the string after formatting and then it will look good and rustfmt should not 'unformat' it.

**Closed by nrc** 2018-06-24 23:33 UTC
Labels: poor-formatting
