### ISSUE TITLE
2018 edition reserved identifiers not supported

### ISSUE THREAD

**Issue by lnicola** [rust-lang-nursery/rustfmt#2801] opened 2018-06-23 07:25 UTC
Clone https://github.com/lnicola/rustfmt-raw-idents and run `cargo fmt`. It will replace `r#async` with `async` and the code will stop building.

**Comment by Mark-Simulacrum** [comment] 2018-06-23 13:52
cc @nrc @Centril  -- this seems like a rather critical bug

**Comment by topecongiro** [comment] 2018-06-24 09:56
This is a duplicate of #2561.

**Closed by topecongiro** 2018-06-24 09:56 UTC
Labels: duplicate
