### ISSUE TITLE
Comments in multiline method chains get dropped

### ISSUE THREAD

**Issue by ijks** [rust-lang-nursery/rustfmt#714] opened 2015-12-20 11:30 UTC
```rust
foo.bar()
   .baz()
   // comment
   .foobar()
```
Becomes:
```rust
foo.bar()
   .baz()
   .foobar()
```

**Comment by marcusklaas** [comment] 2015-12-25 20:05
This is a dupe of https://github.com/rust-lang-nursery/rustfmt/issues/412.

**Closed** 2015-12-25 22:29 UTC
Labels: bug, comments, duplicate
