### ISSUE TITLE
if/else block indentation regression from 0.8.3 to 0.8.4

### ISSUE THREAD

**Issue by sfackler** [rust-lang-nursery/rustfmt#1581] opened 2017-05-24 18:32 UTC
```diff
-        bootstrap.checks.register("PERSISTED_LOCATIONS", move || {
-            if locations2.0.inner_mut.lock().poisoned {
+        bootstrap
+            .checks
+            .register("PERSISTED_LOCATIONS",
+                      move || if locations2.0.inner_mut.lock().poisoned {
                 Check::new(State::Error,
                            "Persisted location storage is poisoned due to a write failure")
             } else {
-                Check::new(State::Healthy, "Persisted location storage is healthy")
-            }
-        });
+                          Check::new(State::Healthy, "Persisted location storage is healthy")
+                      });
```

The else block body and closing braces are properly aligned with the new closure indent level, but the if block body and else line didn't come along.

**Comment by nrc** [comment] 2017-05-24 22:50
Clsoed by #1582

**Comment by nrc** [comment] 2017-05-24 22:51
Oh, perhaps not - only with RFC formatting?

**Comment by topecongiro** [comment] 2017-05-25 07:55
@nrc #1582 only fixes this issue with RFC.
I think this issue and #1580 are duplicate of #1570, that is, using block indent for formatting block (`{...}`) inside visual indent context.

**Closed** 2017-06-01 03:42 UTC
Labels: poor-formatting
