### ISSUE TITLE
Sections of nested chained function calls no longer formatting

### ISSUE THREAD

**Issue by jan-auer** [rust-lang-nursery/rustfmt#3022] opened 2018-09-14 18:32 UTC
After upgrading to the latest rustfmt-preview, `cargo fmt` no longer formats this section of this file which has previously formatted just fine:

https://github.com/getsentry/semaphore/blob/709b2a31173e9677a8615c5463db9d7a2c7371b1/server/src/actors/events.rs#L303-L347

There is no console output and the command exits just fine. I am running _rustfmt 0.99.1-stable (`da17b689` 2018-08-04)_ and _stable rust 1.29.0 (`aa3ca1994` 2018-09-11)_ on _x86_64-apple-darwin_.

I'm wondering if this might have to do with https://github.com/rust-lang-nursery/rustfmt/issues/2932?

**Comment by jan-auer** [comment] 2018-09-14 18:36
Also, I noticed that placing comments between chained calls has the same effect, e.g.:

```rust
// This will format
Some(Some(1))
     .unwrap()
   .unwrap();

Some(Some(1))
    // this will not format
     .unwrap()
   .unwrap();
```

**Comment by topecongiro** [comment] 2018-10-07 06:03
The issue is fixed on the latest master, closing.

It may take a while before the fixed version is available to the stable version.

**Closed by topecongiro** 2018-10-07 06:03 UTC
Labels: poor-formatting
