### ISSUE TITLE
Inconsistent indentations of code in thread::spawn calls

### ISSUE THREAD

**Issue by MoSal** [rust-lang-nursery/rustfmt#816] opened 2016-02-08 03:42 UTC
Indentation of code in `thread::spawn()` calls differ if `join()` is called immediately or not.

Before running rustfmt:

``` rust
use std::thread;

fn main() {
    let _ = thread::spawn(|| {
        println!("Hello World.");
    }).join();

    let t = thread::spawn(|| {
        println!("Hello World.");
    });
    let _ = t.join();
}
```

After running rustfmt:

``` rust
use std::thread;

fn main() {
    let _ = thread::spawn(|| {
                println!("Hello World.");
            })
                .join();

    let t = thread::spawn(|| {
        println!("Hello World.");
    });
    let _ = t.join();
}
```

**Comment by marcusklaas** [comment] 2016-06-04 09:08
This is now formatted as following:
```rust
use std::thread;

fn main() {
    let _ = thread::spawn(|| {
            println!("Hello World.");
        })
        .join();

    let t = thread::spawn(|| {
        println!("Hello World.");
    });
    let _ = t.join();
}
```
The first `spawn` call is still differently when it's followed by `join`, but this is intended behaviour (though subject to discussion) as it makes these chains easier to distinguish from
```rust
    let t = thread::spawn(|| {
        println!("Hello World.");
    });
    join();
```

**Comment by topecongiro** [comment] 2017-06-09 14:04
Closing since this is fixed on the current master.

**Closed by topecongiro** 2017-06-09 14:04 UTC
Labels: poor-formatting
