### ISSUE TITLE
Rustfmt writes a 1 char to long line when formatting expression

### ISSUE THREAD

**Issue by Marwes** [rust-lang-nursery/rustfmt#698] opened 2015-12-13 21:57 UTC
Before 
```
mod test {
    fn test() {
        assert_eq!(e, case(id("x"), vec![
            (Pattern::Record { types: Vec::new(), fields: vec![(intern("y"), None), (intern("x"), Some(intern("z")))] },
                id("z"))
        ]));
    }
}
```
After
```
mod test {
    fn test() {
        assert_eq!(e,
                   case(id("x"),
                        vec![(Pattern::Record {
                                 types: Vec::new(),
                                 fields: vec![(intern("y"), None), (intern("x"), Some(intern("z")))],
                             },
                              id("z"))]));
    }
}
```

Seems that there is an error in calculating how long the expression is somewhere.

**Comment by nrc** [comment] 2015-12-13 22:00
The error here is the extra closing brace and newline?

**Comment by Marwes** [comment] 2015-12-13 22:07
The longest line ends up being 101 characters long after formatting and so I got the warning from rustfmt.

**Comment by nrc** [comment] 2015-12-13 22:08
So, the extra brace is not a bug?

**Comment by Marwes** [comment] 2015-12-13 22:09
Ah no that was me failing to copy paste

**Comment by nrc** [comment] 2016-01-14 05:52
slightly more minimal test case:

```
fn main() {
    Record {
        ffffffffffffffffffffffffffields: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    }
}
```

**Closed** 2016-01-14 18:08 UTC
Labels: poor-formatting
