### ISSUE TITLE
Comments inside function calls get worse

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang-nursery/rustfmt#623] opened 2015-11-17 15:27 UTC
```diff
-            obj = UnwrapObject(obj, /* stopAtOuter = */ 0);
+            obj = UnwrapObject(obj,
+                               // stopAtOuter =
+                               0);
```

**Comment by nrc** [comment] 2015-11-17 20:09
I wonder why we broke the line here at all - it looks like it should fit on one line easily. I wonder if we are breaking *because* of the comment? If so, we shouldn't.

Other than getting better with the line break, I'm not sure there is much we can do here - if we want to change the kind of comment (there is an issue for optionally not doing that) then this is a case where things get worse by doing the 'right' thing.

**Comment by marcusklaas** [comment] 2015-12-02 20:28
This is a dupe of https://github.com/rust-lang-nursery/rustfmt/issues/274.

**Closed by marcusklaas** 2015-12-02 20:28 UTC
Labels: comments, duplicate, poor-formatting
