### ISSUE TITLE
Unnecessary line break with `where` on the same line

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang-nursery/rustfmt#676] opened 2015-12-04 15:13 UTC
```diff
-impl<T> JSTraceable for IpcSender<T> where T: Deserialize + Serialize {
+impl<T> JSTraceable for IpcSender<T> where T: Deserialize + Serialize
+{
```

**Comment by marcusklaas** [comment] 2015-12-04 15:35
Dupe of https://github.com/rust-lang-nursery/rustfmt/issues/650.

**Closed by marcusklaas** 2015-12-04 15:35 UTC
