### ISSUE TITLE
IllFormedSpan error while formatting

### ISSUE THREAD

**Issue by euclio** [rust-lang-nursery/rustfmt#824] opened 2016-02-14 18:25 UTC
Found while formatting https://github.com/Hoverbear/rust-rosetta/blob/master/src/24_game.rs.

```
$ cargo fmt -- --version
0.3.0
```

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: IllFormedSpan(Span { lo: BytePos(1407), hi: BytePos(1404), expn_id: ExpnId(4294967295
) })', ../src/libcore/result.rs:741
stack backtrace:
   1:     0x55cc03ca99f0 - <unknown>
   2:     0x55cc03cabeb5 - <unknown>
   3:     0x55cc03cab930 - <unknown>
   4:     0x55cc03c9d8e3 - <unknown>
   5:     0x55cc03c9dc78 - <unknown>
   6:     0x55cc03ca9051 - <unknown>
   7:     0x55cc03cd8d2f - <unknown>
   8:     0x55cc03aaeb2c - <unknown>
   9:     0x55cc03b1d038 - <unknown>
  10:     0x55cc03b0f84e - <unknown>
  11:     0x55cc03b0f310 - <unknown>
  12:     0x55cc03b05f91 - <unknown>
  13:     0x55cc03a976ea - <unknown>
  14:     0x55cc03aa4d40 - <unknown>
  15:     0x55cc03aa52e2 - <unknown>
  16:     0x55cc03a8a9be - <unknown>
  17:     0x55cc03a91912 - <unknown>
  18:     0x55cc03cab6d4 - <unknown>
  19:     0x55cc03ca8e98 - <unknown>
  20:     0x55cc03cab376 - <unknown>
  21:     0x7ff43b8d460f - __libc_start_main
  22:     0x55cc03a87708 - <unknown>
  23:                0x0 - <unknown>
```

**Comment by marcusklaas** [comment] 2016-03-27 11:56
I cannot reproduce this on the master branch. Closing.

**Closed by marcusklaas** 2016-03-27 11:56 UTC
Labels: bug
