### ISSUE TITLE
Weird chain formatting issues

### ISSUE THREAD

**Issue by RReverser** [rust-lang-nursery/rustfmt#2932] opened 2018-08-17 16:30 UTC
Rustfmt used to chain function calls in a consistent uniform fashion, e.g.:

```rust
fn f() -> Vec<u32> {
    [1, 2, 3]
        .iter()
        .map(|&x| {
            return x * 2;
        })
        .collect()
}
```

But recently something has changed on nightly version and it started breaking the chain like below:

```rust
fn f() -> Vec<u32> {
    [1, 2, 3]
        .iter()
        .map(|&x| {
            return x * 2;
        }).collect()
}
```

**Comment by RReverser** [comment] 2018-08-17 16:32
It looks even more weird if adding another call to the chain:

**stable**
```rust
fn f() -> CustomVec<u32> {
    [1, 2, 3]
        .iter()
        .map(|&x| {
            return x * 2;
        })
        .collect()
        .into()
}
```

**nightly**
```rust
fn f() -> Vec<u32> {
    [1, 2, 3]
        .iter()
        .map(|&x| {
            return x * 2;
        }).collect()
        .into()
}
```

**Comment by crawford** [comment] 2018-08-17 19:08
I've noticed the exact same. My code was previously formatted like this:

```rust
Client::new()
    .request(
        Request::get(&req.state().upstream)
            .header(
                header::ACCEPT,
                HeaderValue::from_static(CONTENT_TYPE_GRAPH_V1),
            )
            .body(Body::empty())
            .expect("unable to form request"),
    )
    .from_err::<Error>()
    .and_then(|res| {
        if res.status().is_success() {
            future::ok(res)
        } else {
            future::err(format_err!(
                "failed to fetch upstream graph: {}",
                res.status()
            ))
        }
    })
    .and_then(|res| res.into_body().concat2().from_err::<Error>())
    .and_then(|body| {
        let graph: Graph = serde_json::from_slice(&body)?;
        Ok(HttpResponse::Ok()
            .content_type(CONTENT_TYPE_GRAPH_V1)
            .body(serde_json::to_string(&graph)?))
    })
```

But new versions of rustfmt prefer the following:

```rust
Client::new()
    .request(
        Request::get(&req.state().upstream)
            .header(
                header::ACCEPT,
                HeaderValue::from_static(CONTENT_TYPE_GRAPH_V1),
            ).body(Body::empty())
            .expect("unable to form request"),
    ).from_err::<Error>()
    .and_then(|res| {
        if res.status().is_success() {
            future::ok(res)
        } else {
            future::err(format_err!(
                "failed to fetch upstream graph: {}",
                res.status()
            ))
        }
    }).and_then(|res| res.into_body().concat2().from_err::<Error>())
    .and_then(|body| {
        let graph: Graph = serde_json::from_slice(&body)?;
        Ok(HttpResponse::Ok()
            .content_type(CONTENT_TYPE_GRAPH_V1)
            .body(serde_json::to_string(&graph)?))
    })
```

I find the latter to be quite difficult to read.

**Comment by azriel91** [comment] 2018-08-17 21:49
From an ergonomics point of view, I tend to use a *duplicate line* shortcut in this kind of code:

```rust
something
    .with_function(|| {
        // ...
    })
    .add_stuff(1) // This is where I'd focus the cursor and duplicate line
    .add_stuff(1) // <- and this pops out, so I can change the argument
    // ...
```

But with the new one

```rust
something
    .with_function(|| {
        // ...
    }).add_stuff(1) // This is where I'd focus the cursor and duplicate line
    }).add_stuff(1) // <- but this pops out, which is broken syntax
    // ...
```

It's true I can go and delete the extra brackets, but it is annoying

**Comment by crawford** [comment] 2018-08-20 03:41
I'm seeing another strange artifact that feels similar:

```diff
                 .txqptr
                 .read()
                 .dmatxqptr()
-                .bits() << 2
+                .bits()
+                << 2
```

**Comment by scampi** [comment] 2018-08-24 07:56
The `chains::join_rewrites` method causes the chain to format as shown by @RReverser. 

Because there is a closure, identified as a block by https://github.com/rust-lang-nursery/rustfmt/blob/4bbfe0829d0ca4579c20c51100bb43c70f7c8e2d/src/chains.rs#L132, the newline is not added:

https://github.com/rust-lang-nursery/rustfmt/blob/4bbfe0829d0ca4579c20c51100bb43c70f7c8e2d/src/chains.rs#L645-L647

@RReverser Looks like the option `indent_style: Visual` would kinda give you what you expect.
@nrc maybe the `is_block_like` method could be changed so that a closure is not recognised as such ? What do you think ?

**Comment by RReverser** [comment] 2018-08-24 12:38
@scampi I don't think special-casing closures would be sufficient, logic needs to be modified more substantially (or removed) since blocks in the middle of chain are formatted equally poorly.

**Comment by scampi** [comment] 2018-08-24 20:40
Can you expand on the formatting of middle chain blocks ? I see the following at the moment:

- a chained method should start on a newline
- a shift operator shouldn't be on a newline, alone

**Comment by nrc** [comment] 2018-08-26 21:53
> I'm seeing another strange artifact that feels similar:

This one is intentional - it was too easy to miss operators which were hidden in the chain.

> blocks in the middle of chain are formatted equally poorly

This was deliberate, but maybe not optimal. I don't remember all the motivations - at the least I thought always putting a newline after `}` was using too much vertical space and `}.foo` was easy enough to scan for. I think there might also have been an orphan issue under certain indentation conditions, but I might be recalling incorrectly. I think it should be easy to experiment by commenting out the `if` line in @scampi 's comment.

**Comment by RReverser** [comment] 2018-08-28 18:31
Oh, it happens not only with closures and block expressions but also structs:

```rust
fn f() -> CustomVec<u32> {
    [1, 2, 3]
        .iter()
        .some_method(S {
            x: 10,
            y: 20,
            z: 30,
        }).collect()
        .into()
}
```

Moreover, it seems that this bug is now happening on stable too :(

**Comment by scampi** [comment] 2018-08-29 10:46
I have commented the `if` mentioned in https://github.com/rust-lang-nursery/rustfmt/issues/2932#issuecomment-415682851 and below are some observations about the [diff](https://github.com/rust-lang-nursery/rustfmt/files/2331784/log.diff.txt) I got when running `cargo test`.

The idea would be to better understand what needs fixing and a basis for further discussion.

# Observations

- Commenting the condition resolved the issue described (see `diff1` and `diff2`). The case shown in https://github.com/rust-lang-nursery/rustfmt/issues/2932#issuecomment-416693452 should also be fixed with that change. The diffs `diff3`, `diff4` and `diff5` depict how it would like in other cases of chained methods.
- `diff6` and `diff7` go against a motivation for removing the newline as explained in https://github.com/rust-lang-nursery/rustfmt/issues/2932#issuecomment-416075204
- `diff8` is a regression with regards to the orphan issue.
- `diff9` shows the impact on ordinals (accessing a tuple value)

In addition to the [ergonomics argument](https://github.com/rust-lang-nursery/rustfmt/issues/2932#issuecomment-413996900), my personal feeling is that removing the newline in cases of method chains (i.e., `diff1..5`) gives a _wavy_ look to the code which hinders readability.

Removing the newline in cases of a block expression (i.e., `diff6..7`) does give a more compact look, while not hindering readability I think.

The lone ordinal as shown in `diff9` may surprise too.

# Examples

## Method Chain

### diff1

```diff
  some_fuuuuuuuuunction()
      .method_call_a(aaaaa, bbbbb, |c| {
          let x = c;
          x
-     }).method_call_b(aaaaa, bbbbb, |c| {
+     })
+     .method_call_b(aaaaa, bbbbb, |c| {
          let x = c;
          x
      });
```

### diff2

```diff
  aaaaaaaaaaaaaaaa
      .map(|x| {
          x += 1;
          x
-      }).filter(some_mod::some_filter)
+      })
+      .filter(some_mod::some_filter)
```

### diff3

```diff
  match inner_meta_item.node {
      ast::MetaItemKind::List(..) => rewrite_path(
          context,
          PathContext::Type,
          None,
          &inner_meta_item.ident,
          shape,
-     ).map_or(false, |s| s.len() + path.len() + 2 <= shape.width),
+     )
+     .map_or(false, |s| s.len() + path.len() + 2 <= shape.width),
      _ => false,
  }
```

### diff4

```diff
  args.iter()
      .filter(|arg| {
          arg.to_expr()
              .map(|e| match e.node {
                  ast::ExprKind::Closure(..) => true,
                  _ => false,
-             }).unwrap_or(false)
-     }).count()
+             })
+             .unwrap_or(false)
+     })
+     .count()
      > 1
```

### diff5

```diff
  {
      match x {
          PushParam => {
              // params are 1-indexed
              stack.push(
                  mparams[match cur.to_digit(10) {
                              Some(d) => d as usize - 1,
                              None => return Err("bad param number".to_owned()),
-                         }].clone(),
+                         }]
+                 .clone(),
              );
          }
      }
  }
```

## Block Expressions

### diff6

```diff
  let x = Foo {
     field1: val1,
     field2: val2,
- }.method_call()
+ }
+ .method_call()
  .method_call();
```

### diff7

```diff
  let y = if cond {
      val1
  } else {
      val2
- }.method_call();
+ }
+ .method_call();
```

## Miscellaneous

### diff8

Regression of https://github.com/rust-lang-nursery/rustfmt/issues/2415

```diff
  let base_url = (|| {
      // stuff

      Ok((|| {
          // stuff
          Some(value.to_string())
-     })().ok_or("")?)
- })().unwrap_or_else(|_: Box<::std::error::Error>| String::from(""));
+     })()
+     .ok_or("")?)
+ })()
+ .unwrap_or_else(|_: Box<::std::error::Error>| String::from(""));
```

### diff9

```diff
  .fold(
      (String::new(), true),
      |(mut s, need_indent), (kind, ref l)| {
          if !l.is_empty() && need_indent {
              s += &indent_str;
          }
          (s + l + "\n", !kind.is_string() || l.ends_with('\\'))
      },
- ).0;
+ )
+ .0;
```

**Closed** 2018-09-19 23:36 UTC
Labels: poor-formatting
