### ISSUE TITLE
Integration tests broken

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#2858] opened 2018-07-23 08:54 UTC
They broke with 71d3d04270474ae0afdeeb410fdcc168a54714b7, but I'm not sure what's called the breakage. Running locally with latest Rust nightly is fine.

**Comment by topecongiro** [comment] 2018-07-25 22:58
Could this be be caused by #2838? That PR changed the default formatting of chains, so there may be formatting diffs around chains, which in result makes `cargo fmt -- --check` emits 1.

**Comment by topecongiro** [comment] 2018-07-25 23:01
I think that integration tests should not fail when there are diffs, only warn that there are diffs and emit those in the log. They should only fail when `cargo test` fails after `cargo fmt -- --all`.

**Comment by gnzlbg** [comment] 2018-07-31 15:01
@topecongiro 

> I think that integration tests should not fail when there are diffs,

Why? `cargo --fmt all && cargo fmt --all -- --check` currently does produce diffs in some situations, but that's marked as a bug: https://github.com/rust-lang-nursery/rustfmt/issues/2787

**Comment by nrc** [comment] 2018-08-01 00:29
These were mostly fixed, but now one of the non-integration tests fails - with `virtualenv: command not found` on OS X.

@gnzlbg the virtualenv line was added as part of integration testing. Do you know what might be happening here?

**Comment by gnzlbg** [comment] 2018-08-01 09:54
@nrc if you take a look at the blame (go to the previous one) that line has been there for a while :/ 
no idea why it was required.  Appears to be a travis-cargo thing and I am only familiar with cargo-travis which does not requires it: https://github.com/roblabla/cargo-travis .

cc @roblabla @CAD97 might know what that line is for (travis-cargo is not maintained anymore AFAIK).

**Comment by topecongiro** [comment] 2018-08-04 09:00
@gnzlbg Thanks for clarifying the situation, I was misunderstanding the intention of that part of CI. The bug reported in #2787 seems VERY weird though, I have no idea what is happening under the hood.

**Comment by topecongiro** [comment] 2018-08-06 06:07
Closes via #2898.

**Closed by topecongiro** 2018-08-06 06:07 UTC
Labels: p-high
