### ISSUE TITLE
Weird formatting on nested funcion calls.

### ISSUE THREAD

**Issue by alatiera** [rust-lang-nursery/rustfmt#2368] opened 2018-01-16 15:08 UTC
I have the following diesel query.

```rust    
select(exists(episode.filter(podcast_id.eq(podcast_id_)).filter(title.eq(title_))))
    .get_result(&*con)
    .map_err(From::from)
```

after rustfmt parses it it ends up like this:

[playground link](https://play.rust-lang.org/?gist=41f45727e1d02ff6012a3c9b45d98c9d&version=stable)

```rust    
select(exists(
    episode
        .filter(podcast_id.eq(podcast_id_))
        .filter(title.eq(title_)),
)).get_result(&*con)
    .map_err(From::from)
```

Now there are a lot of parentheses so here is the rundown of the function, I will indent on each function call for clarity:

```rust
select(             // This is an SQL [select query](http://docs.diesel.rs/diesel/dsl/fn.exists.html)
    exists(         // This is an SQL [exists query](http://docs.diesel.rs/diesel/dsl/fn.exists.html)
        episode     // This is a reperesentation of a SQL Table
            .filter(podcast_id.eq(podcast_id_))     // Method upon the `episode`
            .filter(title.eq(title_)),              // same as above
        )           // This matches with the `exists` call
    )               // This matches with the `select` call
.get_result(&*con)  // This is a method upon the type that `select` will return
.map_err(From::from) // This is method of std::reseult::Result.
```

I am not sure how this could be formatted nicely, but the current way seems a bit alien.

I think I am using nightly-2018-01-14 and the rustfmt of the same day.

**Comment by topecongiro** [comment] 2018-01-17 16:03
The formatted code looks ok to me (though maybe I am just used to `rustfmt`ted code).

One thing you can do is to simplify your expression. e.g.
```rust
// The variable name does not matter, pick whatever you like
let podcasts = episode
    .filter(podcast_id.eq(podcast_id_))
    .filter(title.eq(title_));
select(exists(podcasts))
    .get_result(&*con)
    .map_err(From::from);
```

**Comment by alatiera** [comment] 2018-01-23 15:20
what really bugs me about the current formatting is the way it's indented at the end.

```rust
        .filter(title.eq(title_)),
)).get_result(&*con)
    .map_err(From::from)
```
It feels inconsistent. 
I use #[rustfmt skip] annotation currently and indent it manually but I can't think of a rule-set to avoid it.

**Comment by topecongiro** [comment] 2018-01-24 07:15
The code style for chains is discussed [here](https://github.com/rust-lang-nursery/fmt-rfcs/issues/66). The idea is to avoid 'floating' the element, like:
```rust
        .filter(title.eq(title_)),
))
    .get_result(&*con)
    .map_err(From::from)
```

**Comment by nrc** [comment] 2018-03-18 19:49
Closing since I don't think we can do better - the current formatting is as intended and I think that function calls like this can only be improved by using an intermediate local variable with a descriptive name.

**Closed by nrc** 2018-03-18 19:49 UTC
