### ISSUE TITLE
Invalid installation when using 'cargo install rustfmt-nightly'

### ISSUE THREAD

**Issue by mooman219** [rust-lang-nursery/rustfmt#1957] opened 2017-09-10 22:46 UTC
Not quite sure if this is the correct place to post the issue, but it is rustfmt related.

```
$ rustup show
Default host: x86_64-pc-windows-gnu
nightly-x86_64-pc-windows-gnu (default)
rustc 1.22.0-nightly (ddd123ed9 2017-09-09)
```
On a fresh nightly Rust install via rustup, if you run `cargo install rustfmt-nightly`, you get this error when running `rustfmt`.

`....cargo/bin/rustfmt.exe: error while loading shared libraries: syntax77a88f8172ccd94c.dll: cannot open shared object file: No such file or directory`

The default `cargo install rustfmt` install works fine, aside from it not having the nightly features which is undesirable.

**Comment by nrc** [comment] 2017-09-11 06:35
Are you setting up your LD_LIBRARY_PATH? (See https://github.com/rust-lang-nursery/rustfmt#tips). You might also need to have that directory in your PATH (this might be a regression with loading dynamic libraries in Rust).

**Comment by nrc** [comment] 2017-09-18 04:02
You have to force a re-install after doing a rustup update in order to re-compile with the new toolchain. Could that be your issue?

**Comment by johnthagen** [comment] 2017-10-21 12:16
> You have to force a re-install after doing a rustup update in order to re-compile with the new toolchain. 

@nrc I was just about to create an issue about this, but it sounds like it's a known issue? At least on Windows, every time I `rustup update` and get a new nightly compiler, `rustfmt-nightly` breaks. Is this something that will be fixed in the future?

**Comment by nrc** [comment] 2017-10-26 20:37
Yes, you will need to re-compile Rustfmt every time you update your toolchain (since the compiler version for Rustfmt must match the compiler version for the libraries it depends on). There is no way to fix this in the current distribution model. The long-term fix is distribution with Rustup.

**Closed** 2017-10-26 20:38 UTC
Labels: bug
